import pandas as pd
import os
import csv
import subprocess
import random
import glob
from tqdm import tqdm

#final_compare = pd.DataFrame(columns = ["identifier", "Clk", "cpureg", "memory[0]_f","memory[1]_f","memory[2]_f","memory[3]_f","memory[4]_f","memory[5]_f","memory[6]_f","memory[7]_f","memory[8]_f","memory[9]_f","memory[10]_f","memory[11]_f","memory[12]_f","memory[13]_f","memory[14]_f","memory[15]_f","memory[16]_f","memory[17]_f","memory[18]_f","memory[19]_f","memory[20]_f","memory[21]_f","memory[22]_f","memory[23]_f","memory[24]_f","memory[25]_f","memory[26]_f","memory[27]_f","memory[28]_f","memory[29]_f","memory[30]_f","memory[31]_f","memory[32]_f","memory[33]_f","memory[34]_f","memory[35]_f","memory[36]_f","memory[37]_f","memory[38]_f","memory[39]_f","memory[40]_f","memory[41]_f","memory[42]_f","memory[43]_f","memory[44]_f","memory[45]_f","memory[46]_f","memory[47]_f","memory[48]_f","memory[49]_f","memory[50]_f","memory[51]_f","memory[52]_f","memory[53]_f","memory[54]_f","memory[55]_f","memory[56]_f","memory[57]_f","memory[58]_f","memory[59]_f","memory[60]_f","memory[61]_f","memory[62]_f","memory[63]_f","memory[64]_f","memory[65]_f","memory[66]_f","memory[67]_f","memory[68]_f","memory[69]_f","memory[70]_f","memory[71]_f","memory[72]_f","memory[73]_f","memory[74]_f","memory[75]_f","memory[76]_f","memory[77]_f","memory[78]_f","memory[79]_f","memory[80]_f","memory[81]_f","memory[82]_f","memory[83]_f","memory[84]_f","memory[85]_f","memory[86]_f","memory[87]_f","memory[88]_f","memory[89]_f","memory[90]_f","memory[91]_f","memory[92]_f","memory[93]_f","memory[94]_f","memory[95]_f","memory[96]_f","memory[97]_f","memory[98]_f","memory[99]_f","memory[100]_f","memory[101]_f","memory[102]_f","memory[103]_f","memory[104]_f","memory[105]_f","memory[106]_f","memory[107]_f","memory[108]_f","memory[109]_f","memory[110]_f","memory[111]_f","memory[112]_f","memory[113]_f","memory[114]_f","memory[115]_f","memory[116]_f","memory[117]_f","memory[118]_f","memory[119]_f","memory[120]_f","memory[121]_f","memory[122]_f","memory[123]_f","memory[124]_f","memory[125]_f","memory[126]_f","memory[127]_f","memory[128]_f","memory[129]_f","memory[130]_f","memory[131]_f","memory[132]_f","memory[133]_f","memory[134]_f","memory[135]_f","memory[136]_f","memory[137]_f","memory[138]_f","memory[139]_f","memory[140]_f","memory[141]_f","memory[142]_f","memory[143]_f","memory[144]_f","memory[145]_f","memory[146]_f","memory[147]_f","memory[148]_f","memory[149]_f","memory[150]_f","memory[151]_f","memory[152]_f","memory[153]_f","memory[154]_f","memory[155]_f","memory[156]_f","memory[157]_f","memory[158]_f","memory[159]_f","memory[160]_f","memory[161]_f","memory[162]_f","memory[163]_f","memory[164]_f","memory[165]_f","memory[166]_f","memory[167]_f","memory[168]_f","memory[169]_f","memory[170]_f","memory[171]_f","memory[172]_f","memory[173]_f","memory[174]_f","memory[175]_f","memory[176]_f","memory[177]_f","memory[178]_f","memory[179]_f","memory[180]_f","memory[181]_f","memory[182]_f","memory[183]_f","memory[184]_f","memory[185]_f","memory[186]_f","memory[187]_f","memory[188]_f","memory[189]_f","memory[190]_f","memory[191]_f","memory[192]_f","memory[193]_f","memory[194]_f","memory[195]_f","memory[196]_f","memory[197]_f","memory[198]_f","memory[199]_f","memory[200]_f","memory[201]_f","memory[202]_f","memory[203]_f","memory[204]_f","memory[205]_f","memory[206]_f","memory[207]_f","memory[208]_f","memory[209]_f","memory[210]_f","memory[211]_f","memory[212]_f","memory[213]_f","memory[214]_f","memory[215]_f","memory[216]_f","memory[217]_f","memory[218]_f","memory[219]_f","memory[220]_f","memory[221]_f","memory[222]_f","memory[223]_f","memory[224]_f","memory[225]_f","memory[226]_f","memory[227]_f","memory[228]_f","memory[229]_f","memory[230]_f","memory[231]_f","memory[232]_f","memory[233]_f","memory[234]_f","memory[235]_f","memory[236]_f","memory[237]_f","memory[238]_f","memory[239]_f","memory[240]_f","memory[241]_f","memory[242]_f","memory[243]_f","memory[244]_f","memory[245]_f","memory[246]_f","memory[247]_f","memory[248]_f","memory[249]_f","memory[250]_f","memory[251]_f","memory[252]_f","memory[253]_f","memory[254]_f","memory[255]_f","memory[0]_g","memory[1]_g","memory[2]_g","memory[3]_g","memory[4]_g","memory[5]_g","memory[6]_g","memory[7]_g","memory[8]_g","memory[9]_g","memory[10]_g","memory[11]_g","memory[12]_g","memory[13]_g","memory[14]_g","memory[15]_g","memory[16]_g","memory[17]_g","memory[18]_g","memory[19]_g","memory[20]_g","memory[21]_g","memory[22]_g","memory[23]_g","memory[24]_g","memory[25]_g","memory[26]_g","memory[27]_g","memory[28]_g","memory[29]_g","memory[30]_g","memory[31]_g","memory[32]_g","memory[33]_g","memory[34]_g","memory[35]_g","memory[36]_g","memory[37]_g","memory[38]_g","memory[39]_g","memory[40]_g","memory[41]_g","memory[42]_g","memory[43]_g","memory[44]_g","memory[45]_g","memory[46]_g","memory[47]_g","memory[48]_g","memory[49]_g","memory[50]_g","memory[51]_g","memory[52]_g","memory[53]_g","memory[54]_g","memory[55]_g","memory[56]_g","memory[57]_g","memory[58]_g","memory[59]_g","memory[60]_g","memory[61]_g","memory[62]_g","memory[63]_g","memory[64]_g","memory[65]_g","memory[66]_g","memory[67]_g","memory[68]_g","memory[69]_g","memory[70]_g","memory[71]_g","memory[72]_g","memory[73]_g","memory[74]_g","memory[75]_g","memory[76]_g","memory[77]_g","memory[78]_g","memory[79]_g","memory[80]_g","memory[81]_g","memory[82]_g","memory[83]_g","memory[84]_g","memory[85]_g","memory[86]_g","memory[87]_g","memory[88]_g","memory[89]_g","memory[90]_g","memory[91]_g","memory[92]_g","memory[93]_g","memory[94]_g","memory[95]_g","memory[96]_g","memory[97]_g","memory[98]_g","memory[99]_g","memory[100]_g","memory[101]_g","memory[102]_g","memory[103]_g","memory[104]_g","memory[105]_g","memory[106]_g","memory[107]_g","memory[108]_g","memory[109]_g","memory[110]_g","memory[111]_g","memory[112]_g","memory[113]_g","memory[114]_g","memory[115]_g","memory[116]_g","memory[117]_g","memory[118]_g","memory[119]_g","memory[120]_g","memory[121]_g","memory[122]_g","memory[123]_g","memory[124]_g","memory[125]_g","memory[126]_g","memory[127]_g","memory[128]_g","memory[129]_g","memory[130]_g","memory[131]_g","memory[132]_g","memory[133]_g","memory[134]_g","memory[135]_g","memory[136]_g","memory[137]_g","memory[138]_g","memory[139]_g","memory[140]_g","memory[141]_g","memory[142]_g","memory[143]_g","memory[144]_g","memory[145]_g","memory[146]_g","memory[147]_g","memory[148]_g","memory[149]_g","memory[150]_g","memory[151]_g","memory[152]_g","memory[153]_g","memory[154]_g","memory[155]_g","memory[156]_g","memory[157]_g","memory[158]_g","memory[159]_g","memory[160]_g","memory[161]_g","memory[162]_g","memory[163]_g","memory[164]_g","memory[165]_g","memory[166]_g","memory[167]_g","memory[168]_g","memory[169]_g","memory[170]_g","memory[171]_g","memory[172]_g","memory[173]_g","memory[174]_g","memory[175]_g","memory[176]_g","memory[177]_g","memory[178]_g","memory[179]_g","memory[180]_g","memory[181]_g","memory[182]_g","memory[183]_g","memory[184]_g","memory[185]_g","memory[186]_g","memory[187]_g","memory[188]_g","memory[189]_g","memory[190]_g","memory[191]_g","memory[192]_g","memory[193]_g","memory[194]_g","memory[195]_g","memory[196]_g","memory[197]_g","memory[198]_g","memory[199]_g","memory[200]_g","memory[201]_g","memory[202]_g","memory[203]_g","memory[204]_g","memory[205]_g","memory[206]_g","memory[207]_g","memory[208]_g","memory[209]_g","memory[210]_g","memory[211]_g","memory[212]_g","memory[213]_g","memory[214]_g","memory[215]_g","memory[216]_g","memory[217]_g","memory[218]_g","memory[219]_g","memory[220]_g","memory[221]_g","memory[222]_g","memory[223]_g","memory[224]_g","memory[225]_g","memory[226]_g","memory[227]_g","memory[228]_g","memory[229]_g","memory[230]_g","memory[231]_g","memory[232]_g","memory[233]_g","memory[234]_g","memory[235]_g","memory[236]_g","memory[237]_g","memory[238]_g","memory[239]_g","memory[240]_g","memory[241]_g","memory[242]_g","memory[243]_g","memory[244]_g","memory[245]_g","memory[246]_g","memory[247]_g","memory[248]_g","memory[249]_g","memory[250]_g","memory[251]_g","memory[252]_g","memory[253]_g","memory[254]_g","memory[255]_g"])
final_compare = pd.DataFrame()
#--------------------------------------------------------------------------------
# Extracting the line at which enable is 1
for faulty_csv in tqdm(glob.glob('./results/fault*.csv')):
    #print(faulty_csv) #prints the name of csv

    splitted = faulty_csv.split("_")
    # print(splitted)
    cpureg = splitted[1] + "_" + splitted[2]
    #print(cpureg)
    # print(cpureg)
    identifier =  faulty_csv.split("_", 1)[1].split(".")[0]
    #print(identifier)
    # rows = []

    sf = pd.read_csv(faulty_csv)
    sf = sf.loc[sf['enable'] == 1]
    # print(sf)
    # Clock cycle at which error was enabled *
    time_en = sf.iloc[0,0]
    cf = pd.read_csv('golden_new_loop_with_regs.csv')
# #-----------------------------------------------------------------------------------
    #df = pd.read_csv(faulty_csv)
    for clock in range(0, 100, 10): #(start, end, step size)
        rows = pd.DataFrame()
        temp_df = pd.DataFrame()
        time_outf = time_en + clock
        df = pd.read_csv(faulty_csv)
        df = df.loc[df['clk'] == time_outf].reset_index(drop = True)
        # print("---")
        df = df.iloc[:,:-1]
        # print("###")

        #---------------------------------------------------------------------------------
        # Reading the golden values

        #cf = golden.copy()
        gold = cf[cf["clk"] == time_outf].reset_index(drop = True)
        # print(gold)
        gold = gold.iloc[:,1:-1]

#     # ---------------------------------------------------------------------------------
#     # appending all values in order to form a row

        # rows.append(identifier)
        # rows.append(cpureg)
        # print(rows)
        #print(identifier, cpureg)
        rows["identifier"] = [identifier]
        rows["cpuregs"] = [cpureg]
        #print(rows)
        temp_df = pd.concat([rows, df, gold], axis = 1)

        final_compare = final_compare.append(temp_df)
        # final_compare.to_csv("test1.csv")
# #        final_compare = final_compare.append(pd.Series(rows, index = ["identifier", "Clk", "cpureg", "memory[0]_f","memory[1]_f","memory[2]_f","memory[3]_f","memory[4]_f","memory[5]_f","memory[6]_f","memory[7]_f","memory[8]_f","memory[9]_f","memory[10]_f","memory[11]_f","memory[12]_f","memory[13]_f","memory[14]_f","memory[15]_f","memory[16]_f","memory[17]_f","memory[18]_f","memory[19]_f","memory[20]_f","memory[21]_f","memory[22]_f","memory[23]_f","memory[24]_f","memory[25]_f","memory[26]_f","memory[27]_f","memory[28]_f","memory[29]_f","memory[30]_f","memory[31]_f","memory[32]_f","memory[33]_f","memory[34]_f","memory[35]_f","memory[36]_f","memory[37]_f","memory[38]_f","memory[39]_f","memory[40]_f","memory[41]_f","memory[42]_f","memory[43]_f","memory[44]_f","memory[45]_f","memory[46]_f","memory[47]_f","memory[48]_f","memory[49]_f","memory[50]_f","memory[51]_f","memory[52]_f","memory[53]_f","memory[54]_f","memory[55]_f","memory[56]_f","memory[57]_f","memory[58]_f","memory[59]_f","memory[60]_f","memory[61]_f","memory[62]_f","memory[63]_f","memory[64]_f","memory[65]_f","memory[66]_f","memory[67]_f","memory[68]_f","memory[69]_f","memory[70]_f","memory[71]_f","memory[72]_f","memory[73]_f","memory[74]_f","memory[75]_f","memory[76]_f","memory[77]_f","memory[78]_f","memory[79]_f","memory[80]_f","memory[81]_f","memory[82]_f","memory[83]_f","memory[84]_f","memory[85]_f","memory[86]_f","memory[87]_f","memory[88]_f","memory[89]_f","memory[90]_f","memory[91]_f","memory[92]_f","memory[93]_f","memory[94]_f","memory[95]_f","memory[96]_f","memory[97]_f","memory[98]_f","memory[99]_f","memory[100]_f","memory[101]_f","memory[102]_f","memory[103]_f","memory[104]_f","memory[105]_f","memory[106]_f","memory[107]_f","memory[108]_f","memory[109]_f","memory[110]_f","memory[111]_f","memory[112]_f","memory[113]_f","memory[114]_f","memory[115]_f","memory[116]_f","memory[117]_f","memory[118]_f","memory[119]_f","memory[120]_f","memory[121]_f","memory[122]_f","memory[123]_f","memory[124]_f","memory[125]_f","memory[126]_f","memory[127]_f","memory[128]_f","memory[129]_f","memory[130]_f","memory[131]_f","memory[132]_f","memory[133]_f","memory[134]_f","memory[135]_f","memory[136]_f","memory[137]_f","memory[138]_f","memory[139]_f","memory[140]_f","memory[141]_f","memory[142]_f","memory[143]_f","memory[144]_f","memory[145]_f","memory[146]_f","memory[147]_f","memory[148]_f","memory[149]_f","memory[150]_f","memory[151]_f","memory[152]_f","memory[153]_f","memory[154]_f","memory[155]_f","memory[156]_f","memory[157]_f","memory[158]_f","memory[159]_f","memory[160]_f","memory[161]_f","memory[162]_f","memory[163]_f","memory[164]_f","memory[165]_f","memory[166]_f","memory[167]_f","memory[168]_f","memory[169]_f","memory[170]_f","memory[171]_f","memory[172]_f","memory[173]_f","memory[174]_f","memory[175]_f","memory[176]_f","memory[177]_f","memory[178]_f","memory[179]_f","memory[180]_f","memory[181]_f","memory[182]_f","memory[183]_f","memory[184]_f","memory[185]_f","memory[186]_f","memory[187]_f","memory[188]_f","memory[189]_f","memory[190]_f","memory[191]_f","memory[192]_f","memory[193]_f","memory[194]_f","memory[195]_f","memory[196]_f","memory[197]_f","memory[198]_f","memory[199]_f","memory[200]_f","memory[201]_f","memory[202]_f","memory[203]_f","memory[204]_f","memory[205]_f","memory[206]_f","memory[207]_f","memory[208]_f","memory[209]_f","memory[210]_f","memory[211]_f","memory[212]_f","memory[213]_f","memory[214]_f","memory[215]_f","memory[216]_f","memory[217]_f","memory[218]_f","memory[219]_f","memory[220]_f","memory[221]_f","memory[222]_f","memory[223]_f","memory[224]_f","memory[225]_f","memory[226]_f","memory[227]_f","memory[228]_f","memory[229]_f","memory[230]_f","memory[231]_f","memory[232]_f","memory[233]_f","memory[234]_f","memory[235]_f","memory[236]_f","memory[237]_f","memory[238]_f","memory[239]_f","memory[240]_f","memory[241]_f","memory[242]_f","memory[243]_f","memory[244]_f","memory[245]_f","memory[246]_f","memory[247]_f","memory[248]_f","memory[249]_f","memory[250]_f","memory[251]_f","memory[252]_f","memory[253]_f","memory[254]_f","memory[255]_f","memory[0]_g","memory[1]_g","memory[2]_g","memory[3]_g","memory[4]_g","memory[5]_g","memory[6]_g","memory[7]_g","memory[8]_g","memory[9]_g","memory[10]_g","memory[11]_g","memory[12]_g","memory[13]_g","memory[14]_g","memory[15]_g","memory[16]_g","memory[17]_g","memory[18]_g","memory[19]_g","memory[20]_g","memory[21]_g","memory[22]_g","memory[23]_g","memory[24]_g","memory[25]_g","memory[26]_g","memory[27]_g","memory[28]_g","memory[29]_g","memory[30]_g","memory[31]_g","memory[32]_g","memory[33]_g","memory[34]_g","memory[35]_g","memory[36]_g","memory[37]_g","memory[38]_g","memory[39]_g","memory[40]_g","memory[41]_g","memory[42]_g","memory[43]_g","memory[44]_g","memory[45]_g","memory[46]_g","memory[47]_g","memory[48]_g","memory[49]_g","memory[50]_g","memory[51]_g","memory[52]_g","memory[53]_g","memory[54]_g","memory[55]_g","memory[56]_g","memory[57]_g","memory[58]_g","memory[59]_g","memory[60]_g","memory[61]_g","memory[62]_g","memory[63]_g","memory[64]_g","memory[65]_g","memory[66]_g","memory[67]_g","memory[68]_g","memory[69]_g","memory[70]_g","memory[71]_g","memory[72]_g","memory[73]_g","memory[74]_g","memory[75]_g","memory[76]_g","memory[77]_g","memory[78]_g","memory[79]_g","memory[80]_g","memory[81]_g","memory[82]_g","memory[83]_g","memory[84]_g","memory[85]_g","memory[86]_g","memory[87]_g","memory[88]_g","memory[89]_g","memory[90]_g","memory[91]_g","memory[92]_g","memory[93]_g","memory[94]_g","memory[95]_g","memory[96]_g","memory[97]_g","memory[98]_g","memory[99]_g","memory[100]_g","memory[101]_g","memory[102]_g","memory[103]_g","memory[104]_g","memory[105]_g","memory[106]_g","memory[107]_g","memory[108]_g","memory[109]_g","memory[110]_g","memory[111]_g","memory[112]_g","memory[113]_g","memory[114]_g","memory[115]_g","memory[116]_g","memory[117]_g","memory[118]_g","memory[119]_g","memory[120]_g","memory[121]_g","memory[122]_g","memory[123]_g","memory[124]_g","memory[125]_g","memory[126]_g","memory[127]_g","memory[128]_g","memory[129]_g","memory[130]_g","memory[131]_g","memory[132]_g","memory[133]_g","memory[134]_g","memory[135]_g","memory[136]_g","memory[137]_g","memory[138]_g","memory[139]_g","memory[140]_g","memory[141]_g","memory[142]_g","memory[143]_g","memory[144]_g","memory[145]_g","memory[146]_g","memory[147]_g","memory[148]_g","memory[149]_g","memory[150]_g","memory[151]_g","memory[152]_g","memory[153]_g","memory[154]_g","memory[155]_g","memory[156]_g","memory[157]_g","memory[158]_g","memory[159]_g","memory[160]_g","memory[161]_g","memory[162]_g","memory[163]_g","memory[164]_g","memory[165]_g","memory[166]_g","memory[167]_g","memory[168]_g","memory[169]_g","memory[170]_g","memory[171]_g","memory[172]_g","memory[173]_g","memory[174]_g","memory[175]_g","memory[176]_g","memory[177]_g","memory[178]_g","memory[179]_g","memory[180]_g","memory[181]_g","memory[182]_g","memory[183]_g","memory[184]_g","memory[185]_g","memory[186]_g","memory[187]_g","memory[188]_g","memory[189]_g","memory[190]_g","memory[191]_g","memory[192]_g","memory[193]_g","memory[194]_g","memory[195]_g","memory[196]_g","memory[197]_g","memory[198]_g","memory[199]_g","memory[200]_g","memory[201]_g","memory[202]_g","memory[203]_g","memory[204]_g","memory[205]_g","memory[206]_g","memory[207]_g","memory[208]_g","memory[209]_g","memory[210]_g","memory[211]_g","memory[212]_g","memory[213]_g","memory[214]_g","memory[215]_g","memory[216]_g","memory[217]_g","memory[218]_g","memory[219]_g","memory[220]_g","memory[221]_g","memory[222]_g","memory[223]_g","memory[224]_g","memory[225]_g","memory[226]_g","memory[227]_g","memory[228]_g","memory[229]_g","memory[230]_g","memory[231]_g","memory[232]_g","memory[233]_g","memory[234]_g","memory[235]_g","memory[236]_g","memory[237]_g","memory[238]_g","memory[239]_g","memory[240]_g","memory[241]_g","memory[242]_g","memory[243]_g","memory[244]_g","memory[245]_g","memory[246]_g","memory[247]_g","memory[248]_g","memory[249]_g","memory[250]_g","memory[251]_g","memory[252]_g","memory[253]_g","memory[254]_g","memory[255]_g"]), ignore_index=True)
# # #---------------------------------------------------------------------------------
final_compare = final_compare.reset_index(drop = True)
# print(final_compare.head())
# print(final_compare["cpuregs[1]"])
# print(final_compare["cpuregs[1]_g"])
#
# print(final_compare["cpuregs[1]"] != final_compare["cpuregs[1]_g"])

cpuregs_1_Comp = final_compare["cpuregs[1]"].str.strip() != final_compare["cpuregs[1]_g"].str.strip()
cpuregs_1_Comp = cpuregs_1_Comp.astype(int)
cpuregs_2_Comp = final_compare["cpuregs[2]"].str.strip() != final_compare["cpuregs[2]_g"].str.strip()
cpuregs_2_Comp = cpuregs_2_Comp.astype(int)
cpuregs_3_Comp = final_compare["cpuregs[3]"].str.strip() != final_compare["cpuregs[3]_g"].str.strip()
cpuregs_3_Comp = cpuregs_3_Comp.astype(int)
cpuregs_4_Comp = final_compare["cpuregs[4]"].str.strip() != final_compare["cpuregs[4]_g"].str.strip()
cpuregs_4_Comp = cpuregs_4_Comp.astype(int)
cpuregs_5_Comp = final_compare["cpuregs[5]"].str.strip() != final_compare["cpuregs[5]_g"].str.strip()
cpuregs_5_Comp = cpuregs_5_Comp.astype(int)
cpuregs_6_Comp = final_compare["cpuregs[6]"].str.strip() != final_compare["cpuregs[6]_g"].str.strip()
cpuregs_6_Comp = cpuregs_6_Comp.astype(int)
cpuregs_7_Comp = final_compare["cpuregs[7]"].str.strip() != final_compare["cpuregs[7]_g"].str.strip()
cpuregs_7_Comp = cpuregs_7_Comp.astype(int)

#----------------
#memory values
#older extracting comparison
# dc_listings['price'].astype(str).str.
memory_0_Comp = final_compare["memory[0]"].astype(str).str.strip() != final_compare["memory[0]_g"].astype(str).str.strip()
memory_0_Comp = memory_0_Comp.astype(int)
memory_1_Comp = final_compare["memory[1]"].astype(str).str.strip() != final_compare["memory[1]_g"].astype(str).str.strip()
memory_1_Comp = memory_1_Comp.astype(int)
memory_2_Comp = final_compare["memory[2]"].astype(str).str.strip() != final_compare["memory[2]_g"].astype(str).str.strip()
memory_2_Comp = memory_2_Comp.astype(int)
memory_3_Comp = final_compare["memory[3]"].astype(str).str.strip() != final_compare["memory[3]_g"].astype(str).str.strip()
memory_3_Comp = memory_3_Comp.astype(int)
memory_4_Comp = final_compare["memory[4]"].astype(str).str.strip() != final_compare["memory[4]_g"].astype(str).str.strip()
memory_4_Comp = memory_4_Comp.astype(int)
memory_5_Comp = final_compare["memory[5]"].astype(str).str.strip() != final_compare["memory[5]_g"].astype(str).str.strip()
memory_5_Comp = memory_5_Comp.astype(int)
memory_6_Comp = final_compare["memory[6]"].astype(str).str.strip() != final_compare["memory[6]_g"].astype(str).str.strip()
memory_6_Comp = memory_6_Comp.astype(int)
memory_7_Comp = final_compare["memory[7]"].astype(str).str.strip() != final_compare["memory[7]_g"].astype(str).str.strip()
memory_7_Comp = memory_7_Comp.astype(int)
memory_8_Comp = final_compare["memory[8]"].astype(str).str.strip() != final_compare["memory[8]_g"].astype(str).str.strip()
memory_8_Comp = memory_8_Comp.astype(int)
memory_9_Comp = final_compare["memory[9]"].astype(str).str.strip() != final_compare["memory[9]_g"].astype(str).str.strip()
memory_9_Comp = memory_9_Comp.astype(int)
memory_10_Comp = final_compare["memory[10]"].astype(str).str.strip() != final_compare["memory[10]_g"].astype(str).str.strip()
memory_10_Comp = memory_10_Comp.astype(int)
memory_11_Comp = final_compare["memory[11]"].astype(str).str.strip() != final_compare["memory[11]_g"].astype(str).str.strip()
memory_11_Comp = memory_11_Comp.astype(int)
memory_12_Comp = final_compare["memory[12]"].astype(str).str.strip() != final_compare["memory[12]_g"].astype(str).str.strip()
memory_12_Comp = memory_12_Comp.astype(int)
memory_13_Comp = final_compare["memory[13]"].astype(str).str.strip() != final_compare["memory[13]_g"].astype(str).str.strip()
memory_13_Comp = memory_13_Comp.astype(int)
memory_14_Comp = final_compare["memory[14]"].astype(str).str.strip() != final_compare["memory[14]_g"].astype(str).str.strip()
memory_14_Comp = memory_14_Comp.astype(int)
memory_15_Comp = final_compare["memory[15]"].astype(str).str.strip() != final_compare["memory[15]_g"].astype(str).str.strip()
memory_15_Comp = memory_15_Comp.astype(int)
memory_16_Comp = final_compare["memory[16]"].astype(str).str.strip() != final_compare["memory[16]_g"].astype(str).str.strip()
memory_16_Comp = memory_16_Comp.astype(int)
memory_17_Comp = final_compare["memory[17]"].astype(str).str.strip() != final_compare["memory[17]_g"].astype(str).str.strip()
memory_17_Comp = memory_17_Comp.astype(int)
memory_18_Comp = final_compare["memory[18]"].astype(str).str.strip() != final_compare["memory[18]_g"].astype(str).str.strip()
memory_18_Comp = memory_18_Comp.astype(int)
memory_19_Comp = final_compare["memory[19]"].astype(str).str.strip() != final_compare["memory[19]_g"].astype(str).str.strip()
memory_19_Comp = memory_19_Comp.astype(int)
memory_20_Comp = final_compare["memory[20]"].astype(str).str.strip() != final_compare["memory[20]_g"].astype(str).str.strip()
memory_20_Comp = memory_20_Comp.astype(int)
memory_21_Comp = final_compare["memory[21]"].astype(str).str.strip() != final_compare["memory[21]_g"].astype(str).str.strip()
memory_21_Comp = memory_21_Comp.astype(int)
memory_22_Comp = final_compare["memory[22]"].astype(str).str.strip() != final_compare["memory[22]_g"].astype(str).str.strip()
memory_22_Comp = memory_22_Comp.astype(int)
memory_23_Comp = final_compare["memory[23]"].astype(str).str.strip() != final_compare["memory[23]_g"].astype(str).str.strip()
memory_23_Comp = memory_23_Comp.astype(int)
memory_24_Comp = final_compare["memory[24]"].astype(str).str.strip() != final_compare["memory[24]_g"].astype(str).str.strip()
memory_24_Comp = memory_24_Comp.astype(int)
memory_25_Comp = final_compare["memory[25]"].astype(str).str.strip() != final_compare["memory[25]_g"].astype(str).str.strip()
memory_25_Comp = memory_25_Comp.astype(int)
memory_26_Comp = final_compare["memory[26]"].astype(str).str.strip() != final_compare["memory[26]_g"].astype(str).str.strip()
memory_26_Comp = memory_26_Comp.astype(int)
memory_27_Comp = final_compare["memory[27]"].astype(str).str.strip() != final_compare["memory[27]_g"].astype(str).str.strip()
memory_27_Comp = memory_27_Comp.astype(int)
memory_28_Comp = final_compare["memory[28]"].astype(str).str.strip() != final_compare["memory[28]_g"].astype(str).str.strip()
memory_28_Comp = memory_28_Comp.astype(int)
memory_29_Comp = final_compare["memory[29]"].astype(str).str.strip() != final_compare["memory[29]_g"].astype(str).str.strip()
memory_29_Comp = memory_29_Comp.astype(int)
memory_30_Comp = final_compare["memory[30]"].astype(str).str.strip() != final_compare["memory[30]_g"].astype(str).str.strip()
memory_30_Comp = memory_30_Comp.astype(int)
memory_31_Comp = final_compare["memory[31]"].astype(str).str.strip() != final_compare["memory[31]_g"].astype(str).str.strip()
memory_31_Comp = memory_31_Comp.astype(int)
memory_32_Comp = final_compare["memory[32]"].astype(str).str.strip() != final_compare["memory[32]_g"].astype(str).str.strip()
memory_32_Comp = memory_32_Comp.astype(int)
memory_33_Comp = final_compare["memory[33]"].astype(str).str.strip() != final_compare["memory[33]_g"].astype(str).str.strip()
memory_33_Comp = memory_33_Comp.astype(int)
memory_34_Comp = final_compare["memory[34]"].astype(str).str.strip() != final_compare["memory[34]_g"].astype(str).str.strip()
memory_34_Comp = memory_34_Comp.astype(int)
memory_35_Comp = final_compare["memory[35]"].astype(str).str.strip() != final_compare["memory[35]_g"].astype(str).str.strip()
memory_35_Comp = memory_35_Comp.astype(int)
memory_36_Comp = final_compare["memory[36]"].astype(str).str.strip() != final_compare["memory[36]_g"].astype(str).str.strip()
memory_36_Comp = memory_36_Comp.astype(int)
memory_37_Comp = final_compare["memory[37]"].astype(str).str.strip() != final_compare["memory[37]_g"].astype(str).str.strip()
memory_37_Comp = memory_37_Comp.astype(int)
memory_38_Comp = final_compare["memory[38]"].astype(str).str.strip() != final_compare["memory[38]_g"].astype(str).str.strip()
memory_38_Comp = memory_38_Comp.astype(int)
memory_39_Comp = final_compare["memory[39]"].astype(str).str.strip() != final_compare["memory[39]_g"].astype(str).str.strip()
memory_39_Comp = memory_39_Comp.astype(int)
memory_40_Comp = final_compare["memory[40]"].astype(str).str.strip() != final_compare["memory[40]_g"].astype(str).str.strip()
memory_40_Comp = memory_40_Comp.astype(int)
memory_41_Comp = final_compare["memory[41]"].astype(str).str.strip() != final_compare["memory[41]_g"].astype(str).str.strip()
memory_41_Comp = memory_41_Comp.astype(int)
memory_42_Comp = final_compare["memory[42]"].astype(str).str.strip() != final_compare["memory[42]_g"].astype(str).str.strip()
memory_42_Comp = memory_42_Comp.astype(int)
memory_43_Comp = final_compare["memory[43]"].astype(str).str.strip() != final_compare["memory[43]_g"].astype(str).str.strip()
memory_43_Comp = memory_43_Comp.astype(int)
memory_44_Comp = final_compare["memory[44]"].astype(str).str.strip() != final_compare["memory[44]_g"].astype(str).str.strip()
memory_44_Comp = memory_44_Comp.astype(int)
memory_45_Comp = final_compare["memory[45]"].astype(str).str.strip() != final_compare["memory[45]_g"].astype(str).str.strip()
memory_45_Comp = memory_45_Comp.astype(int)
memory_46_Comp = final_compare["memory[46]"].astype(str).str.strip() != final_compare["memory[46]_g"].astype(str).str.strip()
memory_46_Comp = memory_46_Comp.astype(int)
memory_47_Comp = final_compare["memory[47]"].astype(str).str.strip() != final_compare["memory[47]_g"].astype(str).str.strip()
memory_47_Comp = memory_47_Comp.astype(int)
memory_48_Comp = final_compare["memory[48]"].astype(str).str.strip() != final_compare["memory[48]_g"].astype(str).str.strip()
memory_48_Comp = memory_48_Comp.astype(int)
memory_49_Comp = final_compare["memory[49]"].astype(str).str.strip() != final_compare["memory[49]_g"].astype(str).str.strip()
memory_49_Comp = memory_49_Comp.astype(int)
memory_50_Comp = final_compare["memory[50]"].astype(str).str.strip() != final_compare["memory[50]_g"].astype(str).str.strip()
memory_50_Comp = memory_50_Comp.astype(int)
memory_51_Comp = final_compare["memory[51]"].astype(str).str.strip() != final_compare["memory[51]_g"].astype(str).str.strip()
memory_51_Comp = memory_51_Comp.astype(int)
memory_52_Comp = final_compare["memory[52]"].astype(str).str.strip() != final_compare["memory[52]_g"].astype(str).str.strip()
memory_52_Comp = memory_52_Comp.astype(int)
memory_53_Comp = final_compare["memory[53]"].astype(str).str.strip() != final_compare["memory[53]_g"].astype(str).str.strip()
memory_53_Comp = memory_53_Comp.astype(int)
memory_54_Comp = final_compare["memory[54]"].astype(str).str.strip() != final_compare["memory[54]_g"].astype(str).str.strip()
memory_54_Comp = memory_54_Comp.astype(int)
memory_55_Comp = final_compare["memory[55]"].astype(str).str.strip() != final_compare["memory[55]_g"].astype(str).str.strip()
memory_55_Comp = memory_55_Comp.astype(int)
memory_56_Comp = final_compare["memory[56]"].astype(str).str.strip() != final_compare["memory[56]_g"].astype(str).str.strip()
memory_56_Comp = memory_56_Comp.astype(int)
memory_57_Comp = final_compare["memory[57]"].astype(str).str.strip() != final_compare["memory[57]_g"].astype(str).str.strip()
memory_57_Comp = memory_57_Comp.astype(int)
memory_58_Comp = final_compare["memory[58]"].astype(str).str.strip() != final_compare["memory[58]_g"].astype(str).str.strip()
memory_58_Comp = memory_58_Comp.astype(int)
memory_59_Comp = final_compare["memory[59]"].astype(str).str.strip() != final_compare["memory[59]_g"].astype(str).str.strip()
memory_59_Comp = memory_59_Comp.astype(int)
memory_60_Comp = final_compare["memory[60]"].astype(str).str.strip() != final_compare["memory[60]_g"].astype(str).str.strip()
memory_60_Comp = memory_60_Comp.astype(int)
memory_61_Comp = final_compare["memory[61]"].astype(str).str.strip() != final_compare["memory[61]_g"].astype(str).str.strip()
memory_61_Comp = memory_61_Comp.astype(int)
memory_62_Comp = final_compare["memory[62]"].astype(str).str.strip() != final_compare["memory[62]_g"].astype(str).str.strip()
memory_62_Comp = memory_62_Comp.astype(int)
memory_63_Comp = final_compare["memory[63]"].astype(str).str.strip() != final_compare["memory[63]_g"].astype(str).str.strip()
memory_63_Comp = memory_63_Comp.astype(int)
memory_64_Comp = final_compare["memory[64]"].astype(str).str.strip() != final_compare["memory[64]_g"].astype(str).str.strip()
memory_64_Comp = memory_64_Comp.astype(int)
memory_65_Comp = final_compare["memory[65]"].astype(str).str.strip() != final_compare["memory[65]_g"].astype(str).str.strip()
memory_65_Comp = memory_65_Comp.astype(int)
memory_66_Comp = final_compare["memory[66]"].astype(str).str.strip() != final_compare["memory[66]_g"].astype(str).str.strip()
memory_66_Comp = memory_66_Comp.astype(int)
memory_67_Comp = final_compare["memory[67]"].astype(str).str.strip() != final_compare["memory[67]_g"].astype(str).str.strip()
memory_67_Comp = memory_67_Comp.astype(int)
memory_68_Comp = final_compare["memory[68]"].astype(str).str.strip() != final_compare["memory[68]_g"].astype(str).str.strip()
memory_68_Comp = memory_68_Comp.astype(int)
memory_69_Comp = final_compare["memory[69]"].astype(str).str.strip() != final_compare["memory[69]_g"].astype(str).str.strip()
memory_69_Comp = memory_69_Comp.astype(int)
memory_70_Comp = final_compare["memory[70]"].astype(str).str.strip() != final_compare["memory[70]_g"].astype(str).str.strip()
memory_70_Comp = memory_70_Comp.astype(int)
memory_71_Comp = final_compare["memory[71]"].astype(str).str.strip() != final_compare["memory[71]_g"].astype(str).str.strip()
memory_71_Comp = memory_71_Comp.astype(int)
memory_72_Comp = final_compare["memory[72]"].astype(str).str.strip() != final_compare["memory[72]_g"].astype(str).str.strip()
memory_72_Comp = memory_72_Comp.astype(int)
memory_73_Comp = final_compare["memory[73]"].astype(str).str.strip() != final_compare["memory[73]_g"].astype(str).str.strip()
memory_73_Comp = memory_73_Comp.astype(int)
memory_74_Comp = final_compare["memory[74]"].astype(str).str.strip() != final_compare["memory[74]_g"].astype(str).str.strip()
memory_74_Comp = memory_74_Comp.astype(int)
memory_75_Comp = final_compare["memory[75]"].astype(str).str.strip() != final_compare["memory[75]_g"].astype(str).str.strip()
memory_75_Comp = memory_75_Comp.astype(int)
memory_76_Comp = final_compare["memory[76]"].astype(str).str.strip() != final_compare["memory[76]_g"].astype(str).str.strip()
memory_76_Comp = memory_76_Comp.astype(int)
memory_77_Comp = final_compare["memory[77]"].astype(str).str.strip() != final_compare["memory[77]_g"].astype(str).str.strip()
memory_77_Comp = memory_77_Comp.astype(int)
memory_78_Comp = final_compare["memory[78]"].astype(str).str.strip() != final_compare["memory[78]_g"].astype(str).str.strip()
memory_78_Comp = memory_78_Comp.astype(int)
memory_79_Comp = final_compare["memory[79]"].astype(str).str.strip() != final_compare["memory[79]_g"].astype(str).str.strip()
memory_79_Comp = memory_79_Comp.astype(int)
memory_80_Comp = final_compare["memory[80]"].astype(str).str.strip() != final_compare["memory[80]_g"].astype(str).str.strip()
memory_80_Comp = memory_80_Comp.astype(int)
memory_81_Comp = final_compare["memory[81]"].astype(str).str.strip() != final_compare["memory[81]_g"].astype(str).str.strip()
memory_81_Comp = memory_81_Comp.astype(int)
memory_82_Comp = final_compare["memory[82]"].astype(str).str.strip() != final_compare["memory[82]_g"].astype(str).str.strip()
memory_82_Comp = memory_82_Comp.astype(int)
memory_83_Comp = final_compare["memory[83]"].astype(str).str.strip() != final_compare["memory[83]_g"].astype(str).str.strip()
memory_83_Comp = memory_83_Comp.astype(int)
memory_84_Comp = final_compare["memory[84]"].astype(str).str.strip() != final_compare["memory[84]_g"].astype(str).str.strip()
memory_84_Comp = memory_84_Comp.astype(int)
memory_85_Comp = final_compare["memory[85]"].astype(str).str.strip() != final_compare["memory[85]_g"].astype(str).str.strip()
memory_85_Comp = memory_85_Comp.astype(int)
memory_86_Comp = final_compare["memory[86]"].astype(str).str.strip() != final_compare["memory[86]_g"].astype(str).str.strip()
memory_86_Comp = memory_86_Comp.astype(int)
memory_87_Comp = final_compare["memory[87]"].astype(str).str.strip() != final_compare["memory[87]_g"].astype(str).str.strip()
memory_87_Comp = memory_87_Comp.astype(int)
memory_88_Comp = final_compare["memory[88]"].astype(str).str.strip() != final_compare["memory[88]_g"].astype(str).str.strip()
memory_88_Comp = memory_88_Comp.astype(int)
memory_89_Comp = final_compare["memory[89]"].astype(str).str.strip() != final_compare["memory[89]_g"].astype(str).str.strip()
memory_89_Comp = memory_89_Comp.astype(int)
memory_90_Comp = final_compare["memory[90]"].astype(str).str.strip() != final_compare["memory[90]_g"].astype(str).str.strip()
memory_90_Comp = memory_90_Comp.astype(int)
memory_91_Comp = final_compare["memory[91]"].astype(str).str.strip() != final_compare["memory[91]_g"].astype(str).str.strip()
memory_91_Comp = memory_91_Comp.astype(int)
memory_92_Comp = final_compare["memory[92]"].astype(str).str.strip() != final_compare["memory[92]_g"].astype(str).str.strip()
memory_92_Comp = memory_92_Comp.astype(int)
memory_93_Comp = final_compare["memory[93]"].astype(str).str.strip() != final_compare["memory[93]_g"].astype(str).str.strip()
memory_93_Comp = memory_93_Comp.astype(int)
memory_94_Comp = final_compare["memory[94]"].astype(str).str.strip() != final_compare["memory[94]_g"].astype(str).str.strip()
memory_94_Comp = memory_94_Comp.astype(int)
memory_95_Comp = final_compare["memory[95]"].astype(str).str.strip() != final_compare["memory[95]_g"].astype(str).str.strip()
memory_95_Comp = memory_95_Comp.astype(int)
memory_96_Comp = final_compare["memory[96]"].astype(str).str.strip() != final_compare["memory[96]_g"].astype(str).str.strip()
memory_96_Comp = memory_96_Comp.astype(int)
memory_97_Comp = final_compare["memory[97]"].astype(str).str.strip() != final_compare["memory[97]_g"].astype(str).str.strip()
memory_97_Comp = memory_97_Comp.astype(int)
memory_98_Comp = final_compare["memory[98]"].astype(str).str.strip() != final_compare["memory[98]_g"].astype(str).str.strip()
memory_98_Comp = memory_98_Comp.astype(int)
memory_99_Comp = final_compare["memory[99]"].astype(str).str.strip() != final_compare["memory[99]_g"].astype(str).str.strip()
memory_99_Comp = memory_99_Comp.astype(int)
memory_100_Comp = final_compare["memory[100]"].astype(str).str.strip() != final_compare["memory[100]_g"].astype(str).str.strip()
memory_100_Comp = memory_100_Comp.astype(int)
memory_101_Comp = final_compare["memory[101]"].astype(str).str.strip() != final_compare["memory[101]_g"].astype(str).str.strip()
memory_101_Comp = memory_101_Comp.astype(int)
memory_102_Comp = final_compare["memory[102]"].astype(str).str.strip() != final_compare["memory[102]_g"].astype(str).str.strip()
memory_102_Comp = memory_102_Comp.astype(int)
memory_103_Comp = final_compare["memory[103]"].astype(str).str.strip() != final_compare["memory[103]_g"].astype(str).str.strip()
memory_103_Comp = memory_103_Comp.astype(int)
memory_104_Comp = final_compare["memory[104]"].astype(str).str.strip() != final_compare["memory[104]_g"].astype(str).str.strip()
memory_104_Comp = memory_104_Comp.astype(int)
memory_105_Comp = final_compare["memory[105]"].astype(str).str.strip() != final_compare["memory[105]_g"].astype(str).str.strip()
memory_105_Comp = memory_105_Comp.astype(int)
memory_106_Comp = final_compare["memory[106]"].astype(str).str.strip() != final_compare["memory[106]_g"].astype(str).str.strip()
memory_106_Comp = memory_106_Comp.astype(int)
memory_107_Comp = final_compare["memory[107]"].astype(str).str.strip() != final_compare["memory[107]_g"].astype(str).str.strip()
memory_107_Comp = memory_107_Comp.astype(int)
memory_108_Comp = final_compare["memory[108]"].astype(str).str.strip() != final_compare["memory[108]_g"].astype(str).str.strip()
memory_108_Comp = memory_108_Comp.astype(int)
memory_109_Comp = final_compare["memory[109]"].astype(str).str.strip() != final_compare["memory[109]_g"].astype(str).str.strip()
memory_109_Comp = memory_109_Comp.astype(int)
memory_110_Comp = final_compare["memory[110]"].astype(str).str.strip() != final_compare["memory[110]_g"].astype(str).str.strip()
memory_110_Comp = memory_110_Comp.astype(int)
memory_111_Comp = final_compare["memory[111]"].astype(str).str.strip() != final_compare["memory[111]_g"].astype(str).str.strip()
memory_111_Comp = memory_111_Comp.astype(int)
memory_112_Comp = final_compare["memory[112]"].astype(str).str.strip() != final_compare["memory[112]_g"].astype(str).str.strip()
memory_112_Comp = memory_112_Comp.astype(int)
memory_113_Comp = final_compare["memory[113]"].astype(str).str.strip() != final_compare["memory[113]_g"].astype(str).str.strip()
memory_113_Comp = memory_113_Comp.astype(int)
memory_114_Comp = final_compare["memory[114]"].astype(str).str.strip() != final_compare["memory[114]_g"].astype(str).str.strip()
memory_114_Comp = memory_114_Comp.astype(int)
memory_115_Comp = final_compare["memory[115]"].astype(str).str.strip() != final_compare["memory[115]_g"].astype(str).str.strip()
memory_115_Comp = memory_115_Comp.astype(int)
memory_116_Comp = final_compare["memory[116]"].astype(str).str.strip() != final_compare["memory[116]_g"].astype(str).str.strip()
memory_116_Comp = memory_116_Comp.astype(int)
memory_117_Comp = final_compare["memory[117]"].astype(str).str.strip() != final_compare["memory[117]_g"].astype(str).str.strip()
memory_117_Comp = memory_117_Comp.astype(int)
memory_118_Comp = final_compare["memory[118]"].astype(str).str.strip() != final_compare["memory[118]_g"].astype(str).str.strip()
memory_118_Comp = memory_118_Comp.astype(int)
memory_119_Comp = final_compare["memory[119]"].astype(str).str.strip() != final_compare["memory[119]_g"].astype(str).str.strip()
memory_119_Comp = memory_119_Comp.astype(int)
memory_120_Comp = final_compare["memory[120]"].astype(str).str.strip() != final_compare["memory[120]_g"].astype(str).str.strip()
memory_120_Comp = memory_120_Comp.astype(int)
memory_121_Comp = final_compare["memory[121]"].astype(str).str.strip() != final_compare["memory[121]_g"].astype(str).str.strip()
memory_121_Comp = memory_121_Comp.astype(int)
memory_122_Comp = final_compare["memory[122]"].astype(str).str.strip() != final_compare["memory[122]_g"].astype(str).str.strip()
memory_122_Comp = memory_122_Comp.astype(int)
memory_123_Comp = final_compare["memory[123]"].astype(str).str.strip() != final_compare["memory[123]_g"].astype(str).str.strip()
memory_123_Comp = memory_123_Comp.astype(int)
memory_124_Comp = final_compare["memory[124]"].astype(str).str.strip() != final_compare["memory[124]_g"].astype(str).str.strip()
memory_124_Comp = memory_124_Comp.astype(int)
memory_125_Comp = final_compare["memory[125]"].astype(str).str.strip() != final_compare["memory[125]_g"].astype(str).str.strip()
memory_125_Comp = memory_125_Comp.astype(int)
memory_126_Comp = final_compare["memory[126]"].astype(str).str.strip() != final_compare["memory[126]_g"].astype(str).str.strip()
memory_126_Comp = memory_126_Comp.astype(int)
memory_127_Comp = final_compare["memory[127]"].astype(str).str.strip() != final_compare["memory[127]_g"].astype(str).str.strip()
memory_127_Comp = memory_127_Comp.astype(int)
memory_128_Comp = final_compare["memory[128]"].astype(str).str.strip() != final_compare["memory[128]_g"].astype(str).str.strip()
memory_128_Comp = memory_128_Comp.astype(int)
memory_129_Comp = final_compare["memory[129]"].astype(str).str.strip() != final_compare["memory[129]_g"].astype(str).str.strip()
memory_129_Comp = memory_129_Comp.astype(int)
memory_130_Comp = final_compare["memory[130]"].astype(str).str.strip() != final_compare["memory[130]_g"].astype(str).str.strip()
memory_130_Comp = memory_130_Comp.astype(int)
memory_131_Comp = final_compare["memory[131]"].astype(str).str.strip() != final_compare["memory[131]_g"].astype(str).str.strip()
memory_131_Comp = memory_131_Comp.astype(int)
memory_132_Comp = final_compare["memory[132]"].astype(str).str.strip() != final_compare["memory[132]_g"].astype(str).str.strip()
memory_132_Comp = memory_132_Comp.astype(int)
memory_133_Comp = final_compare["memory[133]"].astype(str).str.strip() != final_compare["memory[133]_g"].astype(str).str.strip()
memory_133_Comp = memory_133_Comp.astype(int)
memory_134_Comp = final_compare["memory[134]"].astype(str).str.strip() != final_compare["memory[134]_g"].astype(str).str.strip()
memory_134_Comp = memory_134_Comp.astype(int)
memory_135_Comp = final_compare["memory[135]"].astype(str).str.strip() != final_compare["memory[135]_g"].astype(str).str.strip()
memory_135_Comp = memory_135_Comp.astype(int)
memory_136_Comp = final_compare["memory[136]"].astype(str).str.strip() != final_compare["memory[136]_g"].astype(str).str.strip()
memory_136_Comp = memory_136_Comp.astype(int)
memory_137_Comp = final_compare["memory[137]"].astype(str).str.strip() != final_compare["memory[137]_g"].astype(str).str.strip()
memory_137_Comp = memory_137_Comp.astype(int)
memory_138_Comp = final_compare["memory[138]"].astype(str).str.strip() != final_compare["memory[138]_g"].astype(str).str.strip()
memory_138_Comp = memory_138_Comp.astype(int)
memory_139_Comp = final_compare["memory[139]"].astype(str).str.strip() != final_compare["memory[139]_g"].astype(str).str.strip()
memory_139_Comp = memory_139_Comp.astype(int)
memory_140_Comp = final_compare["memory[140]"].astype(str).str.strip() != final_compare["memory[140]_g"].astype(str).str.strip()
memory_140_Comp = memory_140_Comp.astype(int)
memory_141_Comp = final_compare["memory[141]"].astype(str).str.strip() != final_compare["memory[141]_g"].astype(str).str.strip()
memory_141_Comp = memory_141_Comp.astype(int)
memory_142_Comp = final_compare["memory[142]"].astype(str).str.strip() != final_compare["memory[142]_g"].astype(str).str.strip()
memory_142_Comp = memory_142_Comp.astype(int)
memory_143_Comp = final_compare["memory[143]"].astype(str).str.strip() != final_compare["memory[143]_g"].astype(str).str.strip()
memory_143_Comp = memory_143_Comp.astype(int)
memory_144_Comp = final_compare["memory[144]"].astype(str).str.strip() != final_compare["memory[144]_g"].astype(str).str.strip()
memory_144_Comp = memory_144_Comp.astype(int)
memory_145_Comp = final_compare["memory[145]"].astype(str).str.strip() != final_compare["memory[145]_g"].astype(str).str.strip()
memory_145_Comp = memory_145_Comp.astype(int)
memory_146_Comp = final_compare["memory[146]"].astype(str).str.strip() != final_compare["memory[146]_g"].astype(str).str.strip()
memory_146_Comp = memory_146_Comp.astype(int)
memory_147_Comp = final_compare["memory[147]"].astype(str).str.strip() != final_compare["memory[147]_g"].astype(str).str.strip()
memory_147_Comp = memory_147_Comp.astype(int)
memory_148_Comp = final_compare["memory[148]"].astype(str).str.strip() != final_compare["memory[148]_g"].astype(str).str.strip()
memory_148_Comp = memory_148_Comp.astype(int)
memory_149_Comp = final_compare["memory[149]"].astype(str).str.strip() != final_compare["memory[149]_g"].astype(str).str.strip()
memory_149_Comp = memory_149_Comp.astype(int)
memory_150_Comp = final_compare["memory[150]"].astype(str).str.strip() != final_compare["memory[150]_g"].astype(str).str.strip()
memory_150_Comp = memory_150_Comp.astype(int)
memory_151_Comp = final_compare["memory[151]"].astype(str).str.strip() != final_compare["memory[151]_g"].astype(str).str.strip()
memory_151_Comp = memory_151_Comp.astype(int)
memory_152_Comp = final_compare["memory[152]"].astype(str).str.strip() != final_compare["memory[152]_g"].astype(str).str.strip()
memory_152_Comp = memory_152_Comp.astype(int)
memory_153_Comp = final_compare["memory[153]"].astype(str).str.strip() != final_compare["memory[153]_g"].astype(str).str.strip()
memory_153_Comp = memory_153_Comp.astype(int)
memory_154_Comp = final_compare["memory[154]"].astype(str).str.strip() != final_compare["memory[154]_g"].astype(str).str.strip()
memory_154_Comp = memory_154_Comp.astype(int)
memory_155_Comp = final_compare["memory[155]"].astype(str).str.strip() != final_compare["memory[155]_g"].astype(str).str.strip()
memory_155_Comp = memory_155_Comp.astype(int)
memory_156_Comp = final_compare["memory[156]"].astype(str).str.strip() != final_compare["memory[156]_g"].astype(str).str.strip()
memory_156_Comp = memory_156_Comp.astype(int)
memory_157_Comp = final_compare["memory[157]"].astype(str).str.strip() != final_compare["memory[157]_g"].astype(str).str.strip()
memory_157_Comp = memory_157_Comp.astype(int)
memory_158_Comp = final_compare["memory[158]"].astype(str).str.strip() != final_compare["memory[158]_g"].astype(str).str.strip()
memory_158_Comp = memory_158_Comp.astype(int)
memory_159_Comp = final_compare["memory[159]"].astype(str).str.strip() != final_compare["memory[159]_g"].astype(str).str.strip()
memory_159_Comp = memory_159_Comp.astype(int)
memory_160_Comp = final_compare["memory[160]"].astype(str).str.strip() != final_compare["memory[160]_g"].astype(str).str.strip()
memory_160_Comp = memory_160_Comp.astype(int)
memory_161_Comp = final_compare["memory[161]"].astype(str).str.strip() != final_compare["memory[161]_g"].astype(str).str.strip()
memory_161_Comp = memory_161_Comp.astype(int)
memory_162_Comp = final_compare["memory[162]"].astype(str).str.strip() != final_compare["memory[162]_g"].astype(str).str.strip()
memory_162_Comp = memory_162_Comp.astype(int)
memory_163_Comp = final_compare["memory[163]"].astype(str).str.strip() != final_compare["memory[163]_g"].astype(str).str.strip()
memory_163_Comp = memory_163_Comp.astype(int)
memory_164_Comp = final_compare["memory[164]"].astype(str).str.strip() != final_compare["memory[164]_g"].astype(str).str.strip()
memory_164_Comp = memory_164_Comp.astype(int)
memory_165_Comp = final_compare["memory[165]"].astype(str).str.strip() != final_compare["memory[165]_g"].astype(str).str.strip()
memory_165_Comp = memory_165_Comp.astype(int)
memory_166_Comp = final_compare["memory[166]"].astype(str).str.strip() != final_compare["memory[166]_g"].astype(str).str.strip()
memory_166_Comp = memory_166_Comp.astype(int)
memory_167_Comp = final_compare["memory[167]"].astype(str).str.strip() != final_compare["memory[167]_g"].astype(str).str.strip()
memory_167_Comp = memory_167_Comp.astype(int)
memory_168_Comp = final_compare["memory[168]"].astype(str).str.strip() != final_compare["memory[168]_g"].astype(str).str.strip()
memory_168_Comp = memory_168_Comp.astype(int)
memory_169_Comp = final_compare["memory[169]"].astype(str).str.strip() != final_compare["memory[169]_g"].astype(str).str.strip()
memory_169_Comp = memory_169_Comp.astype(int)
memory_170_Comp = final_compare["memory[170]"].astype(str).str.strip() != final_compare["memory[170]_g"].astype(str).str.strip()
memory_170_Comp = memory_170_Comp.astype(int)
memory_171_Comp = final_compare["memory[171]"].astype(str).str.strip() != final_compare["memory[171]_g"].astype(str).str.strip()
memory_171_Comp = memory_171_Comp.astype(int)
memory_172_Comp = final_compare["memory[172]"].astype(str).str.strip() != final_compare["memory[172]_g"].astype(str).str.strip()
memory_172_Comp = memory_172_Comp.astype(int)
memory_173_Comp = final_compare["memory[173]"].astype(str).str.strip() != final_compare["memory[173]_g"].astype(str).str.strip()
memory_173_Comp = memory_173_Comp.astype(int)
memory_174_Comp = final_compare["memory[174]"].astype(str).str.strip() != final_compare["memory[174]_g"].astype(str).str.strip()
memory_174_Comp = memory_174_Comp.astype(int)
memory_175_Comp = final_compare["memory[175]"].astype(str).str.strip() != final_compare["memory[175]_g"].astype(str).str.strip()
memory_175_Comp = memory_175_Comp.astype(int)
memory_176_Comp = final_compare["memory[176]"].astype(str).str.strip() != final_compare["memory[176]_g"].astype(str).str.strip()
memory_176_Comp = memory_176_Comp.astype(int)
memory_177_Comp = final_compare["memory[177]"].astype(str).str.strip() != final_compare["memory[177]_g"].astype(str).str.strip()
memory_177_Comp = memory_177_Comp.astype(int)
memory_178_Comp = final_compare["memory[178]"].astype(str).str.strip() != final_compare["memory[178]_g"].astype(str).str.strip()
memory_178_Comp = memory_178_Comp.astype(int)
memory_179_Comp = final_compare["memory[179]"].astype(str).str.strip() != final_compare["memory[179]_g"].astype(str).str.strip()
memory_179_Comp = memory_179_Comp.astype(int)
memory_180_Comp = final_compare["memory[180]"].astype(str).str.strip() != final_compare["memory[180]_g"].astype(str).str.strip()
memory_180_Comp = memory_180_Comp.astype(int)
memory_181_Comp = final_compare["memory[181]"].astype(str).str.strip() != final_compare["memory[181]_g"].astype(str).str.strip()
memory_181_Comp = memory_181_Comp.astype(int)
memory_182_Comp = final_compare["memory[182]"].astype(str).str.strip() != final_compare["memory[182]_g"].astype(str).str.strip()
memory_182_Comp = memory_182_Comp.astype(int)
memory_183_Comp = final_compare["memory[183]"].astype(str).str.strip() != final_compare["memory[183]_g"].astype(str).str.strip()
memory_183_Comp = memory_183_Comp.astype(int)
memory_184_Comp = final_compare["memory[184]"].astype(str).str.strip() != final_compare["memory[184]_g"].astype(str).str.strip()
memory_184_Comp = memory_184_Comp.astype(int)
memory_185_Comp = final_compare["memory[185]"].astype(str).str.strip() != final_compare["memory[185]_g"].astype(str).str.strip()
memory_185_Comp = memory_185_Comp.astype(int)
memory_186_Comp = final_compare["memory[186]"].astype(str).str.strip() != final_compare["memory[186]_g"].astype(str).str.strip()
memory_186_Comp = memory_186_Comp.astype(int)
memory_187_Comp = final_compare["memory[187]"].astype(str).str.strip() != final_compare["memory[187]_g"].astype(str).str.strip()
memory_187_Comp = memory_187_Comp.astype(int)
memory_188_Comp = final_compare["memory[188]"].astype(str).str.strip() != final_compare["memory[188]_g"].astype(str).str.strip()
memory_188_Comp = memory_188_Comp.astype(int)
memory_189_Comp = final_compare["memory[189]"].astype(str).str.strip() != final_compare["memory[189]_g"].astype(str).str.strip()
memory_189_Comp = memory_189_Comp.astype(int)
memory_190_Comp = final_compare["memory[190]"].astype(str).str.strip() != final_compare["memory[190]_g"].astype(str).str.strip()
memory_190_Comp = memory_190_Comp.astype(int)
memory_191_Comp = final_compare["memory[191]"].astype(str).str.strip() != final_compare["memory[191]_g"].astype(str).str.strip()
memory_191_Comp = memory_191_Comp.astype(int)
memory_192_Comp = final_compare["memory[192]"].astype(str).str.strip() != final_compare["memory[192]_g"].astype(str).str.strip()
memory_192_Comp = memory_192_Comp.astype(int)
memory_193_Comp = final_compare["memory[193]"].astype(str).str.strip() != final_compare["memory[193]_g"].astype(str).str.strip()
memory_193_Comp = memory_193_Comp.astype(int)
memory_194_Comp = final_compare["memory[194]"].astype(str).str.strip() != final_compare["memory[194]_g"].astype(str).str.strip()
memory_194_Comp = memory_194_Comp.astype(int)
memory_195_Comp = final_compare["memory[195]"].astype(str).str.strip() != final_compare["memory[195]_g"].astype(str).str.strip()
memory_195_Comp = memory_195_Comp.astype(int)
memory_196_Comp = final_compare["memory[196]"].astype(str).str.strip() != final_compare["memory[196]_g"].astype(str).str.strip()
memory_196_Comp = memory_196_Comp.astype(int)
memory_197_Comp = final_compare["memory[197]"].astype(str).str.strip() != final_compare["memory[197]_g"].astype(str).str.strip()
memory_197_Comp = memory_197_Comp.astype(int)
memory_198_Comp = final_compare["memory[198]"].astype(str).str.strip() != final_compare["memory[198]_g"].astype(str).str.strip()
memory_198_Comp = memory_198_Comp.astype(int)
memory_199_Comp = final_compare["memory[199]"].astype(str).str.strip() != final_compare["memory[199]_g"].astype(str).str.strip()
memory_199_Comp = memory_199_Comp.astype(int)
memory_200_Comp = final_compare["memory[200]"].astype(str).str.strip() != final_compare["memory[200]_g"].astype(str).str.strip()
memory_200_Comp = memory_200_Comp.astype(int)
memory_201_Comp = final_compare["memory[201]"].astype(str).str.strip() != final_compare["memory[201]_g"].astype(str).str.strip()
memory_201_Comp = memory_201_Comp.astype(int)
memory_202_Comp = final_compare["memory[202]"].astype(str).str.strip() != final_compare["memory[202]_g"].astype(str).str.strip()
memory_202_Comp = memory_202_Comp.astype(int)
memory_203_Comp = final_compare["memory[203]"].astype(str).str.strip() != final_compare["memory[203]_g"].astype(str).str.strip()
memory_203_Comp = memory_203_Comp.astype(int)
memory_204_Comp = final_compare["memory[204]"].astype(str).str.strip() != final_compare["memory[204]_g"].astype(str).str.strip()
memory_204_Comp = memory_204_Comp.astype(int)
memory_205_Comp = final_compare["memory[205]"].astype(str).str.strip() != final_compare["memory[205]_g"].astype(str).str.strip()
memory_205_Comp = memory_205_Comp.astype(int)
memory_206_Comp = final_compare["memory[206]"].astype(str).str.strip() != final_compare["memory[206]_g"].astype(str).str.strip()
memory_206_Comp = memory_206_Comp.astype(int)
memory_207_Comp = final_compare["memory[207]"].astype(str).str.strip() != final_compare["memory[207]_g"].astype(str).str.strip()
memory_207_Comp = memory_207_Comp.astype(int)
memory_208_Comp = final_compare["memory[208]"].astype(str).str.strip() != final_compare["memory[208]_g"].astype(str).str.strip()
memory_208_Comp = memory_208_Comp.astype(int)
memory_209_Comp = final_compare["memory[209]"].astype(str).str.strip() != final_compare["memory[209]_g"].astype(str).str.strip()
memory_209_Comp = memory_209_Comp.astype(int)
memory_210_Comp = final_compare["memory[210]"].astype(str).str.strip() != final_compare["memory[210]_g"].astype(str).str.strip()
memory_210_Comp = memory_210_Comp.astype(int)
memory_211_Comp = final_compare["memory[211]"].astype(str).str.strip() != final_compare["memory[211]_g"].astype(str).str.strip()
memory_211_Comp = memory_211_Comp.astype(int)
memory_212_Comp = final_compare["memory[212]"].astype(str).str.strip() != final_compare["memory[212]_g"].astype(str).str.strip()
memory_212_Comp = memory_212_Comp.astype(int)
memory_213_Comp = final_compare["memory[213]"].astype(str).str.strip() != final_compare["memory[213]_g"].astype(str).str.strip()
memory_213_Comp = memory_213_Comp.astype(int)
memory_214_Comp = final_compare["memory[214]"].astype(str).str.strip() != final_compare["memory[214]_g"].astype(str).str.strip()
memory_214_Comp = memory_214_Comp.astype(int)
memory_215_Comp = final_compare["memory[215]"].astype(str).str.strip() != final_compare["memory[215]_g"].astype(str).str.strip()
memory_215_Comp = memory_215_Comp.astype(int)
memory_216_Comp = final_compare["memory[216]"].astype(str).str.strip() != final_compare["memory[216]_g"].astype(str).str.strip()
memory_216_Comp = memory_216_Comp.astype(int)
memory_217_Comp = final_compare["memory[217]"].astype(str).str.strip() != final_compare["memory[217]_g"].astype(str).str.strip()
memory_217_Comp = memory_217_Comp.astype(int)
memory_218_Comp = final_compare["memory[218]"].astype(str).str.strip() != final_compare["memory[218]_g"].astype(str).str.strip()
memory_218_Comp = memory_218_Comp.astype(int)
memory_219_Comp = final_compare["memory[219]"].astype(str).str.strip() != final_compare["memory[219]_g"].astype(str).str.strip()
memory_219_Comp = memory_219_Comp.astype(int)
memory_220_Comp = final_compare["memory[220]"].astype(str).str.strip() != final_compare["memory[220]_g"].astype(str).str.strip()
memory_220_Comp = memory_220_Comp.astype(int)
memory_221_Comp = final_compare["memory[221]"].astype(str).str.strip() != final_compare["memory[221]_g"].astype(str).str.strip()
memory_221_Comp = memory_221_Comp.astype(int)
memory_222_Comp = final_compare["memory[222]"].astype(str).str.strip() != final_compare["memory[222]_g"].astype(str).str.strip()
memory_222_Comp = memory_222_Comp.astype(int)
memory_223_Comp = final_compare["memory[223]"].astype(str).str.strip() != final_compare["memory[223]_g"].astype(str).str.strip()
memory_223_Comp = memory_223_Comp.astype(int)
memory_224_Comp = final_compare["memory[224]"].astype(str).str.strip() != final_compare["memory[224]_g"].astype(str).str.strip()
memory_224_Comp = memory_224_Comp.astype(int)
memory_225_Comp = final_compare["memory[225]"].astype(str).str.strip() != final_compare["memory[225]_g"].astype(str).str.strip()
memory_225_Comp = memory_225_Comp.astype(int)
memory_226_Comp = final_compare["memory[226]"].astype(str).str.strip() != final_compare["memory[226]_g"].astype(str).str.strip()
memory_226_Comp = memory_226_Comp.astype(int)
memory_227_Comp = final_compare["memory[227]"].astype(str).str.strip() != final_compare["memory[227]_g"].astype(str).str.strip()
memory_227_Comp = memory_227_Comp.astype(int)
memory_228_Comp = final_compare["memory[228]"].astype(str).str.strip() != final_compare["memory[228]_g"].astype(str).str.strip()
memory_228_Comp = memory_228_Comp.astype(int)
memory_229_Comp = final_compare["memory[229]"].astype(str).str.strip() != final_compare["memory[229]_g"].astype(str).str.strip()
memory_229_Comp = memory_229_Comp.astype(int)
memory_230_Comp = final_compare["memory[230]"].astype(str).str.strip() != final_compare["memory[230]_g"].astype(str).str.strip()
memory_230_Comp = memory_230_Comp.astype(int)
memory_231_Comp = final_compare["memory[231]"].astype(str).str.strip() != final_compare["memory[231]_g"].astype(str).str.strip()
memory_231_Comp = memory_231_Comp.astype(int)
memory_232_Comp = final_compare["memory[232]"].astype(str).str.strip() != final_compare["memory[232]_g"].astype(str).str.strip()
memory_232_Comp = memory_232_Comp.astype(int)
memory_233_Comp = final_compare["memory[233]"].astype(str).str.strip() != final_compare["memory[233]_g"].astype(str).str.strip()
memory_233_Comp = memory_233_Comp.astype(int)
memory_234_Comp = final_compare["memory[234]"].astype(str).str.strip() != final_compare["memory[234]_g"].astype(str).str.strip()
memory_234_Comp = memory_234_Comp.astype(int)
memory_235_Comp = final_compare["memory[235]"].astype(str).str.strip() != final_compare["memory[235]_g"].astype(str).str.strip()
memory_235_Comp = memory_235_Comp.astype(int)
memory_236_Comp = final_compare["memory[236]"].astype(str).str.strip() != final_compare["memory[236]_g"].astype(str).str.strip()
memory_236_Comp = memory_236_Comp.astype(int)
memory_237_Comp = final_compare["memory[237]"].astype(str).str.strip() != final_compare["memory[237]_g"].astype(str).str.strip()
memory_237_Comp = memory_237_Comp.astype(int)
memory_238_Comp = final_compare["memory[238]"].astype(str).str.strip() != final_compare["memory[238]_g"].astype(str).str.strip()
memory_238_Comp = memory_238_Comp.astype(int)
memory_239_Comp = final_compare["memory[239]"].astype(str).str.strip() != final_compare["memory[239]_g"].astype(str).str.strip()
memory_239_Comp = memory_239_Comp.astype(int)
memory_240_Comp = final_compare["memory[240]"].astype(str).str.strip() != final_compare["memory[240]_g"].astype(str).str.strip()
memory_240_Comp = memory_240_Comp.astype(int)
memory_241_Comp = final_compare["memory[241]"].astype(str).str.strip() != final_compare["memory[241]_g"].astype(str).str.strip()
memory_241_Comp = memory_241_Comp.astype(int)
memory_242_Comp = final_compare["memory[242]"].astype(str).str.strip() != final_compare["memory[242]_g"].astype(str).str.strip()
memory_242_Comp = memory_242_Comp.astype(int)
memory_243_Comp = final_compare["memory[243]"].astype(str).str.strip() != final_compare["memory[243]_g"].astype(str).str.strip()
memory_243_Comp = memory_243_Comp.astype(int)
memory_244_Comp = final_compare["memory[244]"].astype(str).str.strip() != final_compare["memory[244]_g"].astype(str).str.strip()
memory_244_Comp = memory_244_Comp.astype(int)
memory_245_Comp = final_compare["memory[245]"].astype(str).str.strip() != final_compare["memory[245]_g"].astype(str).str.strip()
memory_245_Comp = memory_245_Comp.astype(int)
memory_246_Comp = final_compare["memory[246]"].astype(str).str.strip() != final_compare["memory[246]_g"].astype(str).str.strip()
memory_246_Comp = memory_246_Comp.astype(int)
memory_247_Comp = final_compare["memory[247]"].astype(str).str.strip() != final_compare["memory[247]_g"].astype(str).str.strip()
memory_247_Comp = memory_247_Comp.astype(int)
memory_248_Comp = final_compare["memory[248]"].astype(str).str.strip() != final_compare["memory[248]_g"].astype(str).str.strip()
memory_248_Comp = memory_248_Comp.astype(int)
memory_249_Comp = final_compare["memory[249]"].astype(str).str.strip() != final_compare["memory[249]_g"].astype(str).str.strip()
memory_249_Comp = memory_249_Comp.astype(int)
memory_250_Comp = final_compare["memory[250]"].astype(str).str.strip() != final_compare["memory[250]_g"].astype(str).str.strip()
memory_250_Comp = memory_250_Comp.astype(int)
memory_251_Comp = final_compare["memory[251]"].astype(str).str.strip() != final_compare["memory[251]_g"].astype(str).str.strip()
memory_251_Comp = memory_251_Comp.astype(int)
memory_252_Comp = final_compare["memory[252]"].astype(str).str.strip() != final_compare["memory[252]_g"].astype(str).str.strip()
memory_252_Comp = memory_252_Comp.astype(int)
memory_253_Comp = final_compare["memory[253]"].astype(str).str.strip() != final_compare["memory[253]_g"].astype(str).str.strip()
memory_253_Comp = memory_253_Comp.astype(int)
memory_254_Comp = final_compare["memory[254]"].astype(str).str.strip() != final_compare["memory[254]_g"].astype(str).str.strip()
memory_254_Comp = memory_254_Comp.astype(int)
memory_255_Comp = final_compare["memory[255]"].astype(str).str.strip() != final_compare["memory[255]_g"].astype(str).str.strip()
memory_255_Comp = memory_255_Comp.astype(int)

#-----------
# memory_0_Comp = pd.to_numeric(final_compare['memory[0]'], errors='coerce').isnull() != pd.to_numeric(final_compare['memory[0]_g'], errors='coerce').isnull()
# memory_0_Comp = memory_0_Comp.astype(int)

#final_compare = final_compare.assign(memory_127_Comp = memory_127_Comp.values)

final_compare = final_compare.assign(cpuregs_1_Comp = cpuregs_1_Comp.values)
final_compare = final_compare.assign(cpuregs_2_Comp = cpuregs_2_Comp.values)
final_compare = final_compare.assign(cpuregs_3_Comp = cpuregs_3_Comp.values)
final_compare = final_compare.assign(cpuregs_4_Comp = cpuregs_4_Comp.values)
final_compare = final_compare.assign(cpuregs_5_Comp = cpuregs_5_Comp.values)
final_compare = final_compare.assign(cpuregs_6_Comp = cpuregs_6_Comp.values)
final_compare = final_compare.assign(cpuregs_7_Comp = cpuregs_7_Comp.values)

final_compare = final_compare.assign(memory_0_Comp = memory_0_Comp.values)
final_compare = final_compare.assign(memory_1_Comp = memory_1_Comp.values)
final_compare = final_compare.assign(memory_2_Comp = memory_2_Comp.values)
final_compare = final_compare.assign(memory_3_Comp = memory_3_Comp.values)
final_compare = final_compare.assign(memory_4_Comp = memory_4_Comp.values)
final_compare = final_compare.assign(memory_5_Comp = memory_5_Comp.values)
final_compare = final_compare.assign(memory_6_Comp = memory_6_Comp.values)
final_compare = final_compare.assign(memory_7_Comp = memory_7_Comp.values)
final_compare = final_compare.assign(memory_8_Comp = memory_8_Comp.values)
final_compare = final_compare.assign(memory_9_Comp = memory_9_Comp.values)
final_compare = final_compare.assign(memory_10_Comp = memory_10_Comp.values)
final_compare = final_compare.assign(memory_11_Comp = memory_11_Comp.values)
final_compare = final_compare.assign(memory_12_Comp = memory_12_Comp.values)
final_compare = final_compare.assign(memory_13_Comp = memory_13_Comp.values)
final_compare = final_compare.assign(memory_14_Comp = memory_14_Comp.values)
final_compare = final_compare.assign(memory_15_Comp = memory_15_Comp.values)
final_compare = final_compare.assign(memory_16_Comp = memory_16_Comp.values)
final_compare = final_compare.assign(memory_17_Comp = memory_17_Comp.values)
final_compare = final_compare.assign(memory_18_Comp = memory_18_Comp.values)
final_compare = final_compare.assign(memory_19_Comp = memory_19_Comp.values)
final_compare = final_compare.assign(memory_20_Comp = memory_20_Comp.values)
final_compare = final_compare.assign(memory_21_Comp = memory_21_Comp.values)
final_compare = final_compare.assign(memory_22_Comp = memory_22_Comp.values)
final_compare = final_compare.assign(memory_23_Comp = memory_23_Comp.values)
final_compare = final_compare.assign(memory_24_Comp = memory_24_Comp.values)
final_compare = final_compare.assign(memory_25_Comp = memory_25_Comp.values)
final_compare = final_compare.assign(memory_26_Comp = memory_26_Comp.values)
final_compare = final_compare.assign(memory_27_Comp = memory_27_Comp.values)
final_compare = final_compare.assign(memory_28_Comp = memory_28_Comp.values)
final_compare = final_compare.assign(memory_29_Comp = memory_29_Comp.values)
final_compare = final_compare.assign(memory_30_Comp = memory_30_Comp.values)
final_compare = final_compare.assign(memory_31_Comp = memory_31_Comp.values)
final_compare = final_compare.assign(memory_32_Comp = memory_32_Comp.values)
final_compare = final_compare.assign(memory_33_Comp = memory_33_Comp.values)
final_compare = final_compare.assign(memory_34_Comp = memory_34_Comp.values)
final_compare = final_compare.assign(memory_35_Comp = memory_35_Comp.values)
final_compare = final_compare.assign(memory_36_Comp = memory_36_Comp.values)
final_compare = final_compare.assign(memory_37_Comp = memory_37_Comp.values)
final_compare = final_compare.assign(memory_38_Comp = memory_38_Comp.values)
final_compare = final_compare.assign(memory_39_Comp = memory_39_Comp.values)
final_compare = final_compare.assign(memory_40_Comp = memory_40_Comp.values)
final_compare = final_compare.assign(memory_41_Comp = memory_41_Comp.values)
final_compare = final_compare.assign(memory_42_Comp = memory_42_Comp.values)
final_compare = final_compare.assign(memory_43_Comp = memory_43_Comp.values)
final_compare = final_compare.assign(memory_44_Comp = memory_44_Comp.values)
final_compare = final_compare.assign(memory_45_Comp = memory_45_Comp.values)
final_compare = final_compare.assign(memory_46_Comp = memory_46_Comp.values)
final_compare = final_compare.assign(memory_47_Comp = memory_47_Comp.values)
final_compare = final_compare.assign(memory_48_Comp = memory_48_Comp.values)
final_compare = final_compare.assign(memory_49_Comp = memory_49_Comp.values)
final_compare = final_compare.assign(memory_50_Comp = memory_50_Comp.values)
final_compare = final_compare.assign(memory_51_Comp = memory_51_Comp.values)
final_compare = final_compare.assign(memory_52_Comp = memory_52_Comp.values)
final_compare = final_compare.assign(memory_53_Comp = memory_53_Comp.values)
final_compare = final_compare.assign(memory_54_Comp = memory_54_Comp.values)
final_compare = final_compare.assign(memory_55_Comp = memory_55_Comp.values)
final_compare = final_compare.assign(memory_56_Comp = memory_56_Comp.values)
final_compare = final_compare.assign(memory_57_Comp = memory_57_Comp.values)
final_compare = final_compare.assign(memory_58_Comp = memory_58_Comp.values)
final_compare = final_compare.assign(memory_59_Comp = memory_59_Comp.values)
final_compare = final_compare.assign(memory_60_Comp = memory_60_Comp.values)
final_compare = final_compare.assign(memory_61_Comp = memory_61_Comp.values)
final_compare = final_compare.assign(memory_62_Comp = memory_62_Comp.values)
final_compare = final_compare.assign(memory_63_Comp = memory_63_Comp.values)
final_compare = final_compare.assign(memory_64_Comp = memory_64_Comp.values)
final_compare = final_compare.assign(memory_65_Comp = memory_65_Comp.values)
final_compare = final_compare.assign(memory_66_Comp = memory_66_Comp.values)
final_compare = final_compare.assign(memory_67_Comp = memory_67_Comp.values)
final_compare = final_compare.assign(memory_68_Comp = memory_68_Comp.values)
final_compare = final_compare.assign(memory_69_Comp = memory_69_Comp.values)
final_compare = final_compare.assign(memory_70_Comp = memory_70_Comp.values)
final_compare = final_compare.assign(memory_71_Comp = memory_71_Comp.values)
final_compare = final_compare.assign(memory_72_Comp = memory_72_Comp.values)
final_compare = final_compare.assign(memory_73_Comp = memory_73_Comp.values)
final_compare = final_compare.assign(memory_74_Comp = memory_74_Comp.values)
final_compare = final_compare.assign(memory_75_Comp = memory_75_Comp.values)
final_compare = final_compare.assign(memory_76_Comp = memory_76_Comp.values)
final_compare = final_compare.assign(memory_77_Comp = memory_77_Comp.values)
final_compare = final_compare.assign(memory_78_Comp = memory_78_Comp.values)
final_compare = final_compare.assign(memory_79_Comp = memory_79_Comp.values)
final_compare = final_compare.assign(memory_80_Comp = memory_80_Comp.values)
final_compare = final_compare.assign(memory_81_Comp = memory_81_Comp.values)
final_compare = final_compare.assign(memory_82_Comp = memory_82_Comp.values)
final_compare = final_compare.assign(memory_83_Comp = memory_83_Comp.values)
final_compare = final_compare.assign(memory_84_Comp = memory_84_Comp.values)
final_compare = final_compare.assign(memory_85_Comp = memory_85_Comp.values)
final_compare = final_compare.assign(memory_86_Comp = memory_86_Comp.values)
final_compare = final_compare.assign(memory_87_Comp = memory_87_Comp.values)
final_compare = final_compare.assign(memory_88_Comp = memory_88_Comp.values)
final_compare = final_compare.assign(memory_89_Comp = memory_89_Comp.values)
final_compare = final_compare.assign(memory_90_Comp = memory_90_Comp.values)
final_compare = final_compare.assign(memory_91_Comp = memory_91_Comp.values)
final_compare = final_compare.assign(memory_92_Comp = memory_92_Comp.values)
final_compare = final_compare.assign(memory_93_Comp = memory_93_Comp.values)
final_compare = final_compare.assign(memory_94_Comp = memory_94_Comp.values)
final_compare = final_compare.assign(memory_95_Comp = memory_95_Comp.values)
final_compare = final_compare.assign(memory_96_Comp = memory_96_Comp.values)
final_compare = final_compare.assign(memory_97_Comp = memory_97_Comp.values)
final_compare = final_compare.assign(memory_98_Comp = memory_98_Comp.values)
final_compare = final_compare.assign(memory_99_Comp = memory_99_Comp.values)
final_compare = final_compare.assign(memory_100_Comp = memory_100_Comp.values)
final_compare = final_compare.assign(memory_101_Comp = memory_101_Comp.values)
final_compare = final_compare.assign(memory_102_Comp = memory_102_Comp.values)
final_compare = final_compare.assign(memory_103_Comp = memory_103_Comp.values)
final_compare = final_compare.assign(memory_104_Comp = memory_104_Comp.values)
final_compare = final_compare.assign(memory_105_Comp = memory_105_Comp.values)
final_compare = final_compare.assign(memory_106_Comp = memory_106_Comp.values)
final_compare = final_compare.assign(memory_107_Comp = memory_107_Comp.values)
final_compare = final_compare.assign(memory_108_Comp = memory_108_Comp.values)
final_compare = final_compare.assign(memory_109_Comp = memory_109_Comp.values)
final_compare = final_compare.assign(memory_110_Comp = memory_110_Comp.values)
final_compare = final_compare.assign(memory_111_Comp = memory_111_Comp.values)
final_compare = final_compare.assign(memory_112_Comp = memory_112_Comp.values)
final_compare = final_compare.assign(memory_113_Comp = memory_113_Comp.values)
final_compare = final_compare.assign(memory_114_Comp = memory_114_Comp.values)
final_compare = final_compare.assign(memory_115_Comp = memory_115_Comp.values)
final_compare = final_compare.assign(memory_116_Comp = memory_116_Comp.values)
final_compare = final_compare.assign(memory_117_Comp = memory_117_Comp.values)
final_compare = final_compare.assign(memory_118_Comp = memory_118_Comp.values)
final_compare = final_compare.assign(memory_119_Comp = memory_119_Comp.values)
final_compare = final_compare.assign(memory_120_Comp = memory_120_Comp.values)
final_compare = final_compare.assign(memory_121_Comp = memory_121_Comp.values)
final_compare = final_compare.assign(memory_122_Comp = memory_122_Comp.values)
final_compare = final_compare.assign(memory_123_Comp = memory_123_Comp.values)
final_compare = final_compare.assign(memory_124_Comp = memory_124_Comp.values)
final_compare = final_compare.assign(memory_125_Comp = memory_125_Comp.values)
final_compare = final_compare.assign(memory_126_Comp = memory_126_Comp.values)
final_compare = final_compare.assign(memory_127_Comp = memory_127_Comp.values)
final_compare = final_compare.assign(memory_128_Comp = memory_128_Comp.values)
final_compare = final_compare.assign(memory_129_Comp = memory_129_Comp.values)
final_compare = final_compare.assign(memory_130_Comp = memory_130_Comp.values)
final_compare = final_compare.assign(memory_131_Comp = memory_131_Comp.values)
final_compare = final_compare.assign(memory_132_Comp = memory_132_Comp.values)
final_compare = final_compare.assign(memory_133_Comp = memory_133_Comp.values)
final_compare = final_compare.assign(memory_134_Comp = memory_134_Comp.values)
final_compare = final_compare.assign(memory_135_Comp = memory_135_Comp.values)
final_compare = final_compare.assign(memory_136_Comp = memory_136_Comp.values)
final_compare = final_compare.assign(memory_137_Comp = memory_137_Comp.values)
final_compare = final_compare.assign(memory_138_Comp = memory_138_Comp.values)
final_compare = final_compare.assign(memory_139_Comp = memory_139_Comp.values)
final_compare = final_compare.assign(memory_140_Comp = memory_140_Comp.values)
final_compare = final_compare.assign(memory_141_Comp = memory_141_Comp.values)
final_compare = final_compare.assign(memory_142_Comp = memory_142_Comp.values)
final_compare = final_compare.assign(memory_143_Comp = memory_143_Comp.values)
final_compare = final_compare.assign(memory_144_Comp = memory_144_Comp.values)
final_compare = final_compare.assign(memory_145_Comp = memory_145_Comp.values)
final_compare = final_compare.assign(memory_146_Comp = memory_146_Comp.values)
final_compare = final_compare.assign(memory_147_Comp = memory_147_Comp.values)
final_compare = final_compare.assign(memory_148_Comp = memory_148_Comp.values)
final_compare = final_compare.assign(memory_149_Comp = memory_149_Comp.values)
final_compare = final_compare.assign(memory_150_Comp = memory_150_Comp.values)
final_compare = final_compare.assign(memory_151_Comp = memory_151_Comp.values)
final_compare = final_compare.assign(memory_152_Comp = memory_152_Comp.values)
final_compare = final_compare.assign(memory_153_Comp = memory_153_Comp.values)
final_compare = final_compare.assign(memory_154_Comp = memory_154_Comp.values)
final_compare = final_compare.assign(memory_155_Comp = memory_155_Comp.values)
final_compare = final_compare.assign(memory_156_Comp = memory_156_Comp.values)
final_compare = final_compare.assign(memory_157_Comp = memory_157_Comp.values)
final_compare = final_compare.assign(memory_158_Comp = memory_158_Comp.values)
final_compare = final_compare.assign(memory_159_Comp = memory_159_Comp.values)
final_compare = final_compare.assign(memory_160_Comp = memory_160_Comp.values)
final_compare = final_compare.assign(memory_161_Comp = memory_161_Comp.values)
final_compare = final_compare.assign(memory_162_Comp = memory_162_Comp.values)
final_compare = final_compare.assign(memory_163_Comp = memory_163_Comp.values)
final_compare = final_compare.assign(memory_164_Comp = memory_164_Comp.values)
final_compare = final_compare.assign(memory_165_Comp = memory_165_Comp.values)
final_compare = final_compare.assign(memory_166_Comp = memory_166_Comp.values)
final_compare = final_compare.assign(memory_167_Comp = memory_167_Comp.values)
final_compare = final_compare.assign(memory_168_Comp = memory_168_Comp.values)
final_compare = final_compare.assign(memory_169_Comp = memory_169_Comp.values)
final_compare = final_compare.assign(memory_170_Comp = memory_170_Comp.values)
final_compare = final_compare.assign(memory_171_Comp = memory_171_Comp.values)
final_compare = final_compare.assign(memory_172_Comp = memory_172_Comp.values)
final_compare = final_compare.assign(memory_173_Comp = memory_173_Comp.values)
final_compare = final_compare.assign(memory_174_Comp = memory_174_Comp.values)
final_compare = final_compare.assign(memory_175_Comp = memory_175_Comp.values)
final_compare = final_compare.assign(memory_176_Comp = memory_176_Comp.values)
final_compare = final_compare.assign(memory_177_Comp = memory_177_Comp.values)
final_compare = final_compare.assign(memory_178_Comp = memory_178_Comp.values)
final_compare = final_compare.assign(memory_179_Comp = memory_179_Comp.values)
final_compare = final_compare.assign(memory_180_Comp = memory_180_Comp.values)
final_compare = final_compare.assign(memory_181_Comp = memory_181_Comp.values)
final_compare = final_compare.assign(memory_182_Comp = memory_182_Comp.values)
final_compare = final_compare.assign(memory_183_Comp = memory_183_Comp.values)
final_compare = final_compare.assign(memory_184_Comp = memory_184_Comp.values)
final_compare = final_compare.assign(memory_185_Comp = memory_185_Comp.values)
final_compare = final_compare.assign(memory_186_Comp = memory_186_Comp.values)
final_compare = final_compare.assign(memory_187_Comp = memory_187_Comp.values)
final_compare = final_compare.assign(memory_188_Comp = memory_188_Comp.values)
final_compare = final_compare.assign(memory_189_Comp = memory_189_Comp.values)
final_compare = final_compare.assign(memory_190_Comp = memory_190_Comp.values)
final_compare = final_compare.assign(memory_191_Comp = memory_191_Comp.values)
final_compare = final_compare.assign(memory_192_Comp = memory_192_Comp.values)
final_compare = final_compare.assign(memory_193_Comp = memory_193_Comp.values)
final_compare = final_compare.assign(memory_194_Comp = memory_194_Comp.values)
final_compare = final_compare.assign(memory_195_Comp = memory_195_Comp.values)
final_compare = final_compare.assign(memory_196_Comp = memory_196_Comp.values)
final_compare = final_compare.assign(memory_197_Comp = memory_197_Comp.values)
final_compare = final_compare.assign(memory_198_Comp = memory_198_Comp.values)
final_compare = final_compare.assign(memory_199_Comp = memory_199_Comp.values)
final_compare = final_compare.assign(memory_200_Comp = memory_200_Comp.values)
final_compare = final_compare.assign(memory_201_Comp = memory_201_Comp.values)
final_compare = final_compare.assign(memory_202_Comp = memory_202_Comp.values)
final_compare = final_compare.assign(memory_203_Comp = memory_203_Comp.values)
final_compare = final_compare.assign(memory_204_Comp = memory_204_Comp.values)
final_compare = final_compare.assign(memory_205_Comp = memory_205_Comp.values)
final_compare = final_compare.assign(memory_206_Comp = memory_206_Comp.values)
final_compare = final_compare.assign(memory_207_Comp = memory_207_Comp.values)
final_compare = final_compare.assign(memory_208_Comp = memory_208_Comp.values)
final_compare = final_compare.assign(memory_209_Comp = memory_209_Comp.values)
final_compare = final_compare.assign(memory_210_Comp = memory_210_Comp.values)
final_compare = final_compare.assign(memory_211_Comp = memory_211_Comp.values)
final_compare = final_compare.assign(memory_212_Comp = memory_212_Comp.values)
final_compare = final_compare.assign(memory_213_Comp = memory_213_Comp.values)
final_compare = final_compare.assign(memory_214_Comp = memory_214_Comp.values)
final_compare = final_compare.assign(memory_215_Comp = memory_215_Comp.values)
final_compare = final_compare.assign(memory_216_Comp = memory_216_Comp.values)
final_compare = final_compare.assign(memory_217_Comp = memory_217_Comp.values)
final_compare = final_compare.assign(memory_218_Comp = memory_218_Comp.values)
final_compare = final_compare.assign(memory_219_Comp = memory_219_Comp.values)
final_compare = final_compare.assign(memory_220_Comp = memory_220_Comp.values)
final_compare = final_compare.assign(memory_221_Comp = memory_221_Comp.values)
final_compare = final_compare.assign(memory_222_Comp = memory_222_Comp.values)
final_compare = final_compare.assign(memory_223_Comp = memory_223_Comp.values)
final_compare = final_compare.assign(memory_224_Comp = memory_224_Comp.values)
final_compare = final_compare.assign(memory_225_Comp = memory_225_Comp.values)
final_compare = final_compare.assign(memory_226_Comp = memory_226_Comp.values)
final_compare = final_compare.assign(memory_227_Comp = memory_227_Comp.values)
final_compare = final_compare.assign(memory_228_Comp = memory_228_Comp.values)
final_compare = final_compare.assign(memory_229_Comp = memory_229_Comp.values)
final_compare = final_compare.assign(memory_230_Comp = memory_230_Comp.values)
final_compare = final_compare.assign(memory_231_Comp = memory_231_Comp.values)
final_compare = final_compare.assign(memory_232_Comp = memory_232_Comp.values)
final_compare = final_compare.assign(memory_233_Comp = memory_233_Comp.values)
final_compare = final_compare.assign(memory_234_Comp = memory_234_Comp.values)
final_compare = final_compare.assign(memory_235_Comp = memory_235_Comp.values)
final_compare = final_compare.assign(memory_236_Comp = memory_236_Comp.values)
final_compare = final_compare.assign(memory_237_Comp = memory_237_Comp.values)
final_compare = final_compare.assign(memory_238_Comp = memory_238_Comp.values)
final_compare = final_compare.assign(memory_239_Comp = memory_239_Comp.values)
final_compare = final_compare.assign(memory_240_Comp = memory_240_Comp.values)
final_compare = final_compare.assign(memory_241_Comp = memory_241_Comp.values)
final_compare = final_compare.assign(memory_242_Comp = memory_242_Comp.values)
final_compare = final_compare.assign(memory_243_Comp = memory_243_Comp.values)
final_compare = final_compare.assign(memory_244_Comp = memory_244_Comp.values)
final_compare = final_compare.assign(memory_245_Comp = memory_245_Comp.values)
final_compare = final_compare.assign(memory_246_Comp = memory_246_Comp.values)
final_compare = final_compare.assign(memory_247_Comp = memory_247_Comp.values)
final_compare = final_compare.assign(memory_248_Comp = memory_248_Comp.values)
final_compare = final_compare.assign(memory_249_Comp = memory_249_Comp.values)
final_compare = final_compare.assign(memory_250_Comp = memory_250_Comp.values)
final_compare = final_compare.assign(memory_251_Comp = memory_251_Comp.values)
final_compare = final_compare.assign(memory_252_Comp = memory_252_Comp.values)
final_compare = final_compare.assign(memory_253_Comp = memory_253_Comp.values)
final_compare = final_compare.assign(memory_254_Comp = memory_254_Comp.values)
final_compare = final_compare.assign(memory_255_Comp = memory_255_Comp.values)

#final_compare["M/S"] = final_compare["memory_127_Comp"] + final_compare["memory_250_Comp"]
final_compare["M/S"] = final_compare["cpuregs_1_Comp"]+final_compare["cpuregs_2_Comp"] + final_compare["cpuregs_3_Comp"] +final_compare["cpuregs_4_Comp"] +final_compare["cpuregs_5_Comp"] +final_compare["cpuregs_6_Comp"] +final_compare["cpuregs_7_Comp"] +final_compare["memory_0_Comp"]+final_compare["memory_1_Comp"]+final_compare["memory_2_Comp"] + final_compare["memory_3_Comp"] +final_compare["memory_4_Comp"] +final_compare["memory_5_Comp"] +final_compare["memory_6_Comp"] +final_compare["memory_7_Comp"] +final_compare["memory_8_Comp"] +final_compare["memory_9_Comp"] +final_compare["memory_10_Comp"] +final_compare["memory_11_Comp"] +final_compare["memory_12_Comp"] +final_compare["memory_13_Comp"] +final_compare["memory_14_Comp"] +final_compare["memory_15_Comp"] +final_compare["memory_16_Comp"]+final_compare["memory_17_Comp"]+final_compare["memory_18_Comp"]+final_compare["memory_19_Comp"] +final_compare["memory_20_Comp"]+final_compare["memory_21_Comp"]+final_compare["memory_22_Comp"]+final_compare["memory_23_Comp"] +final_compare["memory_24_Comp"]+final_compare["memory_25_Comp"]+final_compare["memory_26_Comp"]+final_compare["memory_27_Comp"] +final_compare["memory_28_Comp"]+final_compare["memory_29_Comp"]+final_compare["memory_30_Comp"]+final_compare["memory_31_Comp"] +final_compare["memory_32_Comp"]+final_compare["memory_33_Comp"]+final_compare["memory_34_Comp"]+final_compare["memory_35_Comp"] +final_compare["memory_36_Comp"] +final_compare["memory_37_Comp"]+final_compare["memory_38_Comp"]+final_compare["memory_39_Comp"]+final_compare["memory_40_Comp"] +final_compare["memory_41_Comp"]+final_compare["memory_42_Comp"]+final_compare["memory_43_Comp"]+final_compare["memory_44_Comp"] +final_compare["memory_45_Comp"]+final_compare["memory_46_Comp"]+final_compare["memory_47_Comp"]+final_compare["memory_48_Comp"] +final_compare["memory_49_Comp"]+final_compare["memory_50_Comp"]+final_compare["memory_51_Comp"]+final_compare["memory_52_Comp"] +final_compare["memory_53_Comp"]+final_compare["memory_54_Comp"]+final_compare["memory_55_Comp"]+final_compare["memory_56_Comp"] +final_compare["memory_57_Comp"]+final_compare["memory_58_Comp"]+final_compare["memory_59_Comp"]+final_compare["memory_60_Comp"] +final_compare["memory_61_Comp"]+final_compare["memory_62_Comp"]+final_compare["memory_63_Comp"]+final_compare["memory_64_Comp"] +final_compare["memory_65_Comp"]+final_compare["memory_66_Comp"]+final_compare["memory_67_Comp"]+final_compare["memory_68_Comp"] +final_compare["memory_69_Comp"]+final_compare["memory_70_Comp"]+final_compare["memory_71_Comp"]+final_compare["memory_72_Comp"]+final_compare["memory_73_Comp"]+final_compare["memory_74_Comp"]+final_compare["memory_75_Comp"] +final_compare["memory_76_Comp"]+final_compare["memory_77_Comp"]+final_compare["memory_78_Comp"]+final_compare["memory_79_Comp"] +final_compare["memory_80_Comp"]+final_compare["memory_81_Comp"]+final_compare["memory_82_Comp"]+final_compare["memory_83_Comp"] +final_compare["memory_84_Comp"]+final_compare["memory_85_Comp"]+final_compare["memory_86_Comp"]+final_compare["memory_87_Comp"] +final_compare["memory_88_Comp"]+final_compare["memory_89_Comp"]+final_compare["memory_90_Comp"]+final_compare["memory_91_Comp"] +final_compare["memory_92_Comp"]+final_compare["memory_93_Comp"]+final_compare["memory_94_Comp"]+final_compare["memory_95_Comp"] +final_compare["memory_96_Comp"]+final_compare["memory_97_Comp"]+final_compare["memory_98_Comp"]+final_compare["memory_99_Comp"] +final_compare["memory_100_Comp"]+final_compare["memory_101_Comp"]+final_compare["memory_102_Comp"] +final_compare["memory_103_Comp"]+final_compare["memory_104_Comp"]+final_compare["memory_105_Comp"]+final_compare["memory_106_Comp"]+final_compare["memory_107_Comp"]+final_compare["memory_108_Comp"]+final_compare["memory_109_Comp"]+final_compare["memory_110_Comp"]+final_compare["memory_111_Comp"]+final_compare["memory_112_Comp"]+final_compare["memory_113_Comp"]+final_compare["memory_114_Comp"]+final_compare["memory_115_Comp"] +final_compare["memory_116_Comp"] +final_compare["memory_117_Comp"]+final_compare["memory_118_Comp"]+final_compare["memory_119_Comp"] +final_compare["memory_120_Comp"]+final_compare["memory_121_Comp"]+final_compare["memory_122_Comp"]+final_compare["memory_123_Comp"] +final_compare["memory_124_Comp"] +final_compare["memory_125_Comp"]+final_compare["memory_126_Comp"]+final_compare["memory_127_Comp"] +final_compare["memory_128_Comp"]+final_compare["memory_129_Comp"]+final_compare["memory_130_Comp"]+final_compare["memory_131_Comp"] +final_compare["memory_132_Comp"] +final_compare["memory_133_Comp"]+final_compare["memory_134_Comp"]+final_compare["memory_135_Comp"] +final_compare["memory_136_Comp"]+final_compare["memory_137_Comp"]+final_compare["memory_138_Comp"]+final_compare["memory_139_Comp"] +final_compare["memory_140_Comp"] +final_compare["memory_141_Comp"]+final_compare["memory_142_Comp"]+final_compare["memory_143_Comp"] +final_compare["memory_144_Comp"]+final_compare["memory_145_Comp"]+final_compare["memory_146_Comp"]+final_compare["memory_147_Comp"] +final_compare["memory_148_Comp"] +final_compare["memory_149_Comp"]+final_compare["memory_150_Comp"]+final_compare["memory_151_Comp"] +final_compare["memory_152_Comp"]+final_compare["memory_153_Comp"]+final_compare["memory_154_Comp"]+final_compare["memory_155_Comp"] +final_compare["memory_156_Comp"] +final_compare["memory_157_Comp"]+final_compare["memory_158_Comp"]+final_compare["memory_159_Comp"] +final_compare["memory_160_Comp"]+final_compare["memory_161_Comp"]+final_compare["memory_162_Comp"]+final_compare["memory_163_Comp"] +final_compare["memory_164_Comp"] +final_compare["memory_165_Comp"]+final_compare["memory_166_Comp"]+final_compare["memory_167_Comp"] +final_compare["memory_168_Comp"]+final_compare["memory_169_Comp"]+final_compare["memory_170_Comp"]+final_compare["memory_171_Comp"] +final_compare["memory_172_Comp"] +final_compare["memory_173_Comp"] +final_compare["memory_174_Comp"] +final_compare["memory_175_Comp"] +final_compare["memory_176_Comp"]+final_compare["memory_177_Comp"]+final_compare["memory_178_Comp"] +final_compare["memory_179_Comp"]+final_compare["memory_180_Comp"]+final_compare["memory_181_Comp"]+final_compare["memory_182_Comp"] +final_compare["memory_183_Comp"] +final_compare["memory_184_Comp"]+final_compare["memory_185_Comp"]+final_compare["memory_186_Comp"] +final_compare["memory_187_Comp"]+final_compare["memory_188_Comp"]+final_compare["memory_189_Comp"]+final_compare["memory_190_Comp"] +final_compare["memory_191_Comp"] +final_compare["memory_192_Comp"]+final_compare["memory_193_Comp"]+final_compare["memory_194_Comp"] +final_compare["memory_195_Comp"]+final_compare["memory_196_Comp"]+final_compare["memory_197_Comp"]+final_compare["memory_198_Comp"] +final_compare["memory_199_Comp"] +final_compare["memory_200_Comp"]+final_compare["memory_201_Comp"]+final_compare["memory_202_Comp"] +final_compare["memory_203_Comp"]+final_compare["memory_204_Comp"]+final_compare["memory_205_Comp"]+final_compare["memory_206_Comp"] +final_compare["memory_207_Comp"] +final_compare["memory_208_Comp"]+final_compare["memory_209_Comp"]+final_compare["memory_210_Comp"] +final_compare["memory_211_Comp"]+final_compare["memory_212_Comp"]+final_compare["memory_213_Comp"]+final_compare["memory_214_Comp"] +final_compare["memory_215_Comp"] +final_compare["memory_216_Comp"]+final_compare["memory_217_Comp"]+final_compare["memory_218_Comp"] +final_compare["memory_219_Comp"]+final_compare["memory_220_Comp"]+final_compare["memory_221_Comp"]+final_compare["memory_222_Comp"] +final_compare["memory_223_Comp"] +final_compare["memory_224_Comp"] +final_compare["memory_225_Comp"]+final_compare["memory_226_Comp"]+final_compare["memory_227_Comp"] +final_compare["memory_228_Comp"]+final_compare["memory_229_Comp"]+final_compare["memory_230_Comp"]+final_compare["memory_231_Comp"] +final_compare["memory_232_Comp"] +final_compare["memory_233_Comp"]+final_compare["memory_234_Comp"]+final_compare["memory_235_Comp"] +final_compare["memory_236_Comp"]+final_compare["memory_237_Comp"]+final_compare["memory_238_Comp"]+final_compare["memory_239_Comp"] +final_compare["memory_240_Comp"] +final_compare["memory_241_Comp"]+final_compare["memory_242_Comp"]+final_compare["memory_243_Comp"] +final_compare["memory_244_Comp"]+final_compare["memory_245_Comp"]+final_compare["memory_246_Comp"]+final_compare["memory_247_Comp"] +final_compare["memory_248_Comp"] +final_compare["memory_249_Comp"]+final_compare["memory_250_Comp"]+final_compare["memory_251_Comp"] +final_compare["memory_252_Comp"]+final_compare["memory_253_Comp"]+final_compare["memory_254_Comp"]+final_compare["memory_255_Comp"]
final_compare.loc[final_compare['identifier'].duplicated(), 'identifier'] = ''
# print(final_compare)
final_compare.to_csv("compare_with_regs_paper2.csv", index= False)



