import pandas as pd
import os
import csv
import subprocess
import random
import glob
from tqdm import tqdm

final_compare = pd.DataFrame()
final_compare= pd.read_csv("inter_sim3.csv", dtype=str)

final_compare.dropna(axis = 0, how = "any", inplace=True)
final_compare.reset_index(drop=True, inplace=True)

#----------------
#memory values

memory_92_Comp = final_compare["memory[92]"].astype(str).str.strip() != final_compare["memory[92]_g"].astype(str).str.strip()
memory_92_Comp = memory_92_Comp.astype(int)
memory_93_Comp = final_compare["memory[93]"].astype(str).str.strip() != final_compare["memory[93]_g"].astype(str).str.strip()
memory_93_Comp = memory_93_Comp.astype(int)
memory_94_Comp = final_compare["memory[94]"].astype(str).str.strip() != final_compare["memory[94]_g"].astype(str).str.strip()
memory_94_Comp = memory_94_Comp.astype(int)
memory_95_Comp = final_compare["memory[95]"].astype(str).str.strip() != final_compare["memory[95]_g"].astype(str).str.strip()
memory_95_Comp = memory_95_Comp.astype(int)
memory_96_Comp = final_compare["memory[96]"].astype(str).str.strip() != final_compare["memory[96]_g"].astype(str).str.strip()
memory_96_Comp = memory_96_Comp.astype(int)
memory_97_Comp = final_compare["memory[97]"].astype(str).str.strip() != final_compare["memory[97]_g"].astype(str).str.strip()
memory_97_Comp = memory_97_Comp.astype(int)
memory_98_Comp = final_compare["memory[98]"].astype(str).str.strip() != final_compare["memory[98]_g"].astype(str).str.strip()
memory_98_Comp = memory_98_Comp.astype(int)
memory_99_Comp = final_compare["memory[99]"].astype(str).str.strip() != final_compare["memory[99]_g"].astype(str).str.strip()
memory_99_Comp = memory_99_Comp.astype(int)
memory_100_Comp = final_compare["memory[100]"].astype(str).str.strip() != final_compare["memory[100]_g"].astype(str).str.strip()
memory_100_Comp = memory_100_Comp.astype(int)
memory_101_Comp = final_compare["memory[101]"].astype(str).str.strip() != final_compare["memory[101]_g"].astype(str).str.strip()
memory_101_Comp = memory_101_Comp.astype(int)
memory_102_Comp = final_compare["memory[102]"].astype(str).str.strip() != final_compare["memory[102]_g"].astype(str).str.strip()
memory_102_Comp = memory_102_Comp.astype(int)
memory_103_Comp = final_compare["memory[103]"].astype(str).str.strip() != final_compare["memory[103]_g"].astype(str).str.strip()
memory_103_Comp = memory_103_Comp.astype(int)
memory_104_Comp = final_compare["memory[104]"].astype(str).str.strip() != final_compare["memory[104]_g"].astype(str).str.strip()
memory_104_Comp = memory_104_Comp.astype(int)
memory_105_Comp = final_compare["memory[105]"].astype(str).str.strip() != final_compare["memory[105]_g"].astype(str).str.strip()
memory_105_Comp = memory_105_Comp.astype(int)
memory_106_Comp = final_compare["memory[106]"].astype(str).str.strip() != final_compare["memory[106]_g"].astype(str).str.strip()
memory_106_Comp = memory_106_Comp.astype(int)
memory_107_Comp = final_compare["memory[107]"].astype(str).str.strip() != final_compare["memory[107]_g"].astype(str).str.strip()
memory_107_Comp = memory_107_Comp.astype(int)
memory_108_Comp = final_compare["memory[108]"].astype(str).str.strip() != final_compare["memory[108]_g"].astype(str).str.strip()
memory_108_Comp = memory_108_Comp.astype(int)
memory_109_Comp = final_compare["memory[109]"].astype(str).str.strip() != final_compare["memory[109]_g"].astype(str).str.strip()
memory_109_Comp = memory_109_Comp.astype(int)
memory_110_Comp = final_compare["memory[110]"].astype(str).str.strip() != final_compare["memory[110]_g"].astype(str).str.strip()
memory_110_Comp = memory_110_Comp.astype(int)

memory_120_Comp = final_compare["memory[120]"].astype(str).str.strip() != final_compare["memory[120]_g"].astype(str).str.strip()
memory_120_Comp = memory_120_Comp.astype(int)
memory_121_Comp = final_compare["memory[121]"].astype(str).str.strip() != final_compare["memory[121]_g"].astype(str).str.strip()
memory_121_Comp = memory_121_Comp.astype(int)
memory_122_Comp = final_compare["memory[122]"].astype(str).str.strip() != final_compare["memory[122]_g"].astype(str).str.strip()
memory_122_Comp = memory_122_Comp.astype(int)
memory_123_Comp = final_compare["memory[123]"].astype(str).str.strip() != final_compare["memory[123]_g"].astype(str).str.strip()
memory_123_Comp = memory_123_Comp.astype(int)
memory_124_Comp = final_compare["memory[124]"].astype(str).str.strip() != final_compare["memory[124]_g"].astype(str).str.strip()
memory_124_Comp = memory_124_Comp.astype(int)
memory_125_Comp = final_compare["memory[125]"].astype(str).str.strip() != final_compare["memory[125]_g"].astype(str).str.strip()
memory_125_Comp = memory_125_Comp.astype(int)

memory_155_Comp = final_compare["memory[155]"].astype(str).str.strip() != final_compare["memory[155]_g"].astype(str).str.strip()
memory_155_Comp = memory_155_Comp.astype(int)
memory_156_Comp = final_compare["memory[156]"].astype(str).str.strip() != final_compare["memory[156]_g"].astype(str).str.strip()
memory_156_Comp = memory_156_Comp.astype(int)
memory_157_Comp = final_compare["memory[157]"].astype(str).str.strip() != final_compare["memory[157]_g"].astype(str).str.strip()
memory_157_Comp = memory_157_Comp.astype(int)
memory_158_Comp = final_compare["memory[158]"].astype(str).str.strip() != final_compare["memory[158]_g"].astype(str).str.strip()
memory_158_Comp = memory_158_Comp.astype(int)
memory_159_Comp = final_compare["memory[159]"].astype(str).str.strip() != final_compare["memory[159]_g"].astype(str).str.strip()
memory_159_Comp = memory_159_Comp.astype(int)
memory_160_Comp = final_compare["memory[160]"].astype(str).str.strip() != final_compare["memory[160]_g"].astype(str).str.strip()
memory_160_Comp = memory_160_Comp.astype(int)

memory_184_Comp = final_compare["memory[184]"].astype(str).str.strip() != final_compare["memory[184]_g"].astype(str).str.strip()
memory_184_Comp = memory_184_Comp.astype(int)
memory_185_Comp = final_compare["memory[185]"].astype(str).str.strip() != final_compare["memory[185]_g"].astype(str).str.strip()
memory_185_Comp = memory_185_Comp.astype(int)
memory_186_Comp = final_compare["memory[186]"].astype(str).str.strip() != final_compare["memory[186]_g"].astype(str).str.strip()
memory_186_Comp = memory_186_Comp.astype(int)
memory_187_Comp = final_compare["memory[187]"].astype(str).str.strip() != final_compare["memory[187]_g"].astype(str).str.strip()
memory_187_Comp = memory_187_Comp.astype(int)
memory_188_Comp = final_compare["memory[188]"].astype(str).str.strip() != final_compare["memory[188]_g"].astype(str).str.strip()
memory_188_Comp = memory_188_Comp.astype(int)
memory_189_Comp = final_compare["memory[189]"].astype(str).str.strip() != final_compare["memory[189]_g"].astype(str).str.strip()
memory_189_Comp = memory_189_Comp.astype(int)
memory_190_Comp = final_compare["memory[190]"].astype(str).str.strip() != final_compare["memory[190]_g"].astype(str).str.strip()
memory_190_Comp = memory_190_Comp.astype(int)
memory_191_Comp = final_compare["memory[191]"].astype(str).str.strip() != final_compare["memory[191]_g"].astype(str).str.strip()
memory_191_Comp = memory_191_Comp.astype(int)
memory_192_Comp = final_compare["memory[192]"].astype(str).str.strip() != final_compare["memory[192]_g"].astype(str).str.strip()
memory_192_Comp = memory_192_Comp.astype(int)
memory_193_Comp = final_compare["memory[193]"].astype(str).str.strip() != final_compare["memory[193]_g"].astype(str).str.strip()
memory_193_Comp = memory_193_Comp.astype(int)
memory_194_Comp = final_compare["memory[194]"].astype(str).str.strip() != final_compare["memory[194]_g"].astype(str).str.strip()
memory_194_Comp = memory_194_Comp.astype(int)
memory_195_Comp = final_compare["memory[195]"].astype(str).str.strip() != final_compare["memory[195]_g"].astype(str).str.strip()
memory_195_Comp = memory_195_Comp.astype(int)
memory_196_Comp = final_compare["memory[196]"].astype(str).str.strip() != final_compare["memory[196]_g"].astype(str).str.strip()
memory_196_Comp = memory_196_Comp.astype(int)
memory_197_Comp = final_compare["memory[197]"].astype(str).str.strip() != final_compare["memory[197]_g"].astype(str).str.strip()
memory_197_Comp = memory_197_Comp.astype(int)

#------------------------------------------------------------------------------------------------------------------------------
final_compare = final_compare.assign(memory_92_Comp = memory_92_Comp.values)
final_compare = final_compare.assign(memory_93_Comp = memory_93_Comp.values)
final_compare = final_compare.assign(memory_94_Comp = memory_94_Comp.values)
final_compare = final_compare.assign(memory_95_Comp = memory_95_Comp.values)
final_compare = final_compare.assign(memory_96_Comp = memory_96_Comp.values)
final_compare = final_compare.assign(memory_97_Comp = memory_97_Comp.values)
final_compare = final_compare.assign(memory_98_Comp = memory_98_Comp.values)
final_compare = final_compare.assign(memory_99_Comp = memory_99_Comp.values)
final_compare = final_compare.assign(memory_100_Comp = memory_100_Comp.values)
final_compare = final_compare.assign(memory_101_Comp = memory_101_Comp.values)
final_compare = final_compare.assign(memory_102_Comp = memory_102_Comp.values)
final_compare = final_compare.assign(memory_103_Comp = memory_103_Comp.values)
final_compare = final_compare.assign(memory_104_Comp = memory_104_Comp.values)
final_compare = final_compare.assign(memory_105_Comp = memory_105_Comp.values)
final_compare = final_compare.assign(memory_106_Comp = memory_106_Comp.values)
final_compare = final_compare.assign(memory_107_Comp = memory_107_Comp.values)
final_compare = final_compare.assign(memory_108_Comp = memory_108_Comp.values)
final_compare = final_compare.assign(memory_109_Comp = memory_109_Comp.values)
final_compare = final_compare.assign(memory_110_Comp = memory_110_Comp.values)

final_compare = final_compare.assign(memory_120_Comp = memory_120_Comp.values)
final_compare = final_compare.assign(memory_121_Comp = memory_121_Comp.values)
final_compare = final_compare.assign(memory_122_Comp = memory_122_Comp.values)
final_compare = final_compare.assign(memory_123_Comp = memory_123_Comp.values)
final_compare = final_compare.assign(memory_124_Comp = memory_124_Comp.values)
final_compare = final_compare.assign(memory_125_Comp = memory_125_Comp.values)


final_compare = final_compare.assign(memory_155_Comp = memory_155_Comp.values)
final_compare = final_compare.assign(memory_156_Comp = memory_156_Comp.values)
final_compare = final_compare.assign(memory_157_Comp = memory_157_Comp.values)
final_compare = final_compare.assign(memory_158_Comp = memory_158_Comp.values)
final_compare = final_compare.assign(memory_159_Comp = memory_159_Comp.values)
final_compare = final_compare.assign(memory_160_Comp = memory_160_Comp.values)

final_compare = final_compare.assign(memory_184_Comp = memory_184_Comp.values)
final_compare = final_compare.assign(memory_185_Comp = memory_185_Comp.values)
final_compare = final_compare.assign(memory_186_Comp = memory_186_Comp.values)
final_compare = final_compare.assign(memory_187_Comp = memory_187_Comp.values)
final_compare = final_compare.assign(memory_188_Comp = memory_188_Comp.values)
final_compare = final_compare.assign(memory_189_Comp = memory_189_Comp.values)
final_compare = final_compare.assign(memory_190_Comp = memory_190_Comp.values)
final_compare = final_compare.assign(memory_191_Comp = memory_191_Comp.values)
final_compare = final_compare.assign(memory_192_Comp = memory_192_Comp.values)
final_compare = final_compare.assign(memory_193_Comp = memory_193_Comp.values)
final_compare = final_compare.assign(memory_194_Comp = memory_194_Comp.values)
final_compare = final_compare.assign(memory_195_Comp = memory_195_Comp.values)
final_compare = final_compare.assign(memory_196_Comp = memory_196_Comp.values)
final_compare = final_compare.assign(memory_197_Comp = memory_197_Comp.values)

#final_compare["M/S"] = final_compare["memory_127_Comp"] + final_compare["memory_250_Comp"]
final_compare["M/S"] = final_compare["memory_92_Comp"]+final_compare["memory_93_Comp"]+final_compare["memory_94_Comp"]+final_compare["memory_95_Comp"] +final_compare["memory_96_Comp"]+final_compare["memory_97_Comp"]+final_compare["memory_98_Comp"]+final_compare["memory_99_Comp"] +final_compare["memory_100_Comp"]+final_compare["memory_101_Comp"]+final_compare["memory_102_Comp"] +final_compare["memory_103_Comp"]+final_compare["memory_104_Comp"]+final_compare["memory_105_Comp"]+final_compare["memory_106_Comp"]+final_compare["memory_107_Comp"]+final_compare["memory_108_Comp"]+final_compare["memory_109_Comp"]+final_compare["memory_110_Comp"]+final_compare["memory_120_Comp"]+final_compare["memory_121_Comp"]+final_compare["memory_122_Comp"]+final_compare["memory_123_Comp"] +final_compare["memory_124_Comp"] +final_compare["memory_125_Comp"]+final_compare["memory_155_Comp"] +final_compare["memory_156_Comp"] +final_compare["memory_157_Comp"]+final_compare["memory_158_Comp"]+final_compare["memory_159_Comp"] +final_compare["memory_160_Comp"] +final_compare["memory_184_Comp"]+final_compare["memory_185_Comp"]+final_compare["memory_186_Comp"] +final_compare["memory_187_Comp"]+final_compare["memory_188_Comp"]+final_compare["memory_189_Comp"]+final_compare["memory_190_Comp"] +final_compare["memory_191_Comp"] +final_compare["memory_192_Comp"]+final_compare["memory_193_Comp"]+final_compare["memory_194_Comp"] +final_compare["memory_195_Comp"]+final_compare["memory_196_Comp"]+final_compare["memory_197_Comp"]#+final_compare["memory_198_Comp"] +final_compare["memory_199_Comp"] +final_compare["memory_200_Comp"]+final_compare["memory_201_Comp"]+final_compare["memory_202_Comp"] +final_compare["memory_203_Comp"]+final_compare["memory_204_Comp"]+final_compare["memory_205_Comp"]+final_compare["memory_206_Comp"] +final_compare["memory_207_Comp"] +final_compare["memory_208_Comp"]+final_compare["memory_209_Comp"]+final_compare["memory_210_Comp"] +final_compare["memory_211_Comp"]+final_compare["memory_212_Comp"]+final_compare["memory_213_Comp"]+final_compare["memory_214_Comp"] +final_compare["memory_215_Comp"] +final_compare["memory_216_Comp"]+final_compare["memory_217_Comp"]+final_compare["memory_218_Comp"] +final_compare["memory_219_Comp"]+final_compare["memory_220_Comp"]+final_compare["memory_221_Comp"]+final_compare["memory_222_Comp"] +final_compare["memory_223_Comp"] +final_compare["memory_224_Comp"] +final_compare["memory_225_Comp"]+final_compare["memory_226_Comp"]+final_compare["memory_227_Comp"] +final_compare["memory_228_Comp"]+final_compare["memory_229_Comp"]+final_compare["memory_230_Comp"]+final_compare["memory_231_Comp"] +final_compare["memory_232_Comp"] +final_compare["memory_233_Comp"]+final_compare["memory_234_Comp"]+final_compare["memory_235_Comp"] +final_compare["memory_236_Comp"]+final_compare["memory_237_Comp"]+final_compare["memory_238_Comp"]+final_compare["memory_239_Comp"] +final_compare["memory_240_Comp"] +final_compare["memory_241_Comp"]+final_compare["memory_242_Comp"]+final_compare["memory_243_Comp"] +final_compare["memory_244_Comp"]+final_compare["memory_245_Comp"]+final_compare["memory_246_Comp"]+final_compare["memory_247_Comp"] +final_compare["memory_248_Comp"] +final_compare["memory_249_Comp"]+final_compare["memory_250_Comp"]+final_compare["memory_251_Comp"] +final_compare["memory_252_Comp"]+final_compare["memory_253_Comp"]+final_compare["memory_254_Comp"]+final_compare["memory_255_Comp"]
# final_compare.loc[final_compare['identifier'].duplicated(), 'identifier'] = ''
# print(final_compare)
# print(final_compare.head())
final_compare.to_csv("compare_with_regs_sim3.csv", index= False)
