import pandas as pd
import os
import csv
import subprocess
import random
import glob
from tqdm import tqdm

final_compare = pd.DataFrame()
final_compare= pd.read_csv("inter_sim2.csv", dtype=str)
final_compare.dropna(axis = 0, how = "any", inplace=True)
final_compare.reset_index(drop=True, inplace=True)

#----------------
#memory values
memory_38_Comp = final_compare["memory[38]"].astype(str).str.strip() != final_compare["memory[38]_g"].astype(str).str.strip()
memory_38_Comp = memory_38_Comp.astype(int)
memory_39_Comp = final_compare["memory[39]"].astype(str).str.strip() != final_compare["memory[39]_g"].astype(str).str.strip()
memory_39_Comp = memory_39_Comp.astype(int)
memory_40_Comp = final_compare["memory[40]"].astype(str).str.strip() != final_compare["memory[40]_g"].astype(str).str.strip()
memory_40_Comp = memory_40_Comp.astype(int)
memory_41_Comp = final_compare["memory[41]"].astype(str).str.strip() != final_compare["memory[41]_g"].astype(str).str.strip()
memory_41_Comp = memory_41_Comp.astype(int)
memory_42_Comp = final_compare["memory[42]"].astype(str).str.strip() != final_compare["memory[42]_g"].astype(str).str.strip()
memory_42_Comp = memory_42_Comp.astype(int)
memory_43_Comp = final_compare["memory[43]"].astype(str).str.strip() != final_compare["memory[43]_g"].astype(str).str.strip()
memory_43_Comp = memory_43_Comp.astype(int)
memory_44_Comp = final_compare["memory[44]"].astype(str).str.strip() != final_compare["memory[44]_g"].astype(str).str.strip()
memory_44_Comp = memory_44_Comp.astype(int)
memory_45_Comp = final_compare["memory[45]"].astype(str).str.strip() != final_compare["memory[45]_g"].astype(str).str.strip()
memory_45_Comp = memory_45_Comp.astype(int)
memory_46_Comp = final_compare["memory[46]"].astype(str).str.strip() != final_compare["memory[46]_g"].astype(str).str.strip()
memory_46_Comp = memory_46_Comp.astype(int)
memory_47_Comp = final_compare["memory[47]"].astype(str).str.strip() != final_compare["memory[47]_g"].astype(str).str.strip()
memory_47_Comp = memory_47_Comp.astype(int)
memory_48_Comp = final_compare["memory[48]"].astype(str).str.strip() != final_compare["memory[48]_g"].astype(str).str.strip()
memory_48_Comp = memory_48_Comp.astype(int)
memory_49_Comp = final_compare["memory[49]"].astype(str).str.strip() != final_compare["memory[49]_g"].astype(str).str.strip()
memory_49_Comp = memory_49_Comp.astype(int)
memory_50_Comp = final_compare["memory[50]"].astype(str).str.strip() != final_compare["memory[50]_g"].astype(str).str.strip()
memory_50_Comp = memory_50_Comp.astype(int)
memory_51_Comp = final_compare["memory[51]"].astype(str).str.strip() != final_compare["memory[51]_g"].astype(str).str.strip()
memory_51_Comp = memory_51_Comp.astype(int)
memory_52_Comp = final_compare["memory[52]"].astype(str).str.strip() != final_compare["memory[52]_g"].astype(str).str.strip()
memory_52_Comp = memory_52_Comp.astype(int)
memory_53_Comp = final_compare["memory[53]"].astype(str).str.strip() != final_compare["memory[53]_g"].astype(str).str.strip()
memory_53_Comp = memory_53_Comp.astype(int)
memory_54_Comp = final_compare["memory[54]"].astype(str).str.strip() != final_compare["memory[54]_g"].astype(str).str.strip()
memory_54_Comp = memory_54_Comp.astype(int)
memory_55_Comp = final_compare["memory[55]"].astype(str).str.strip() != final_compare["memory[55]_g"].astype(str).str.strip()
memory_55_Comp = memory_55_Comp.astype(int)
memory_56_Comp = final_compare["memory[56]"].astype(str).str.strip() != final_compare["memory[56]_g"].astype(str).str.strip()
memory_56_Comp = memory_56_Comp.astype(int)
memory_57_Comp = final_compare["memory[57]"].astype(str).str.strip() != final_compare["memory[57]_g"].astype(str).str.strip()
memory_57_Comp = memory_57_Comp.astype(int)
memory_58_Comp = final_compare["memory[58]"].astype(str).str.strip() != final_compare["memory[58]_g"].astype(str).str.strip()
memory_58_Comp = memory_58_Comp.astype(int)
memory_59_Comp = final_compare["memory[59]"].astype(str).str.strip() != final_compare["memory[59]_g"].astype(str).str.strip()
memory_59_Comp = memory_59_Comp.astype(int)
memory_60_Comp = final_compare["memory[60]"].astype(str).str.strip() != final_compare["memory[60]_g"].astype(str).str.strip()
memory_60_Comp = memory_60_Comp.astype(int)
memory_61_Comp = final_compare["memory[61]"].astype(str).str.strip() != final_compare["memory[61]_g"].astype(str).str.strip()
memory_61_Comp = memory_61_Comp.astype(int)
memory_62_Comp = final_compare["memory[62]"].astype(str).str.strip() != final_compare["memory[62]_g"].astype(str).str.strip()
memory_62_Comp = memory_62_Comp.astype(int)
memory_63_Comp = final_compare["memory[63]"].astype(str).str.strip() != final_compare["memory[63]_g"].astype(str).str.strip()
memory_63_Comp = memory_63_Comp.astype(int)
memory_64_Comp = final_compare["memory[64]"].astype(str).str.strip() != final_compare["memory[64]_g"].astype(str).str.strip()
memory_64_Comp = memory_64_Comp.astype(int)
memory_65_Comp = final_compare["memory[65]"].astype(str).str.strip() != final_compare["memory[65]_g"].astype(str).str.strip()
memory_65_Comp = memory_65_Comp.astype(int)
memory_66_Comp = final_compare["memory[66]"].astype(str).str.strip() != final_compare["memory[66]_g"].astype(str).str.strip()
memory_66_Comp = memory_66_Comp.astype(int)
memory_67_Comp = final_compare["memory[67]"].astype(str).str.strip() != final_compare["memory[67]_g"].astype(str).str.strip()
memory_67_Comp = memory_67_Comp.astype(int)
memory_68_Comp = final_compare["memory[68]"].astype(str).str.strip() != final_compare["memory[68]_g"].astype(str).str.strip()
memory_68_Comp = memory_68_Comp.astype(int)
memory_69_Comp = final_compare["memory[69]"].astype(str).str.strip() != final_compare["memory[69]_g"].astype(str).str.strip()
memory_69_Comp = memory_69_Comp.astype(int)
memory_70_Comp = final_compare["memory[70]"].astype(str).str.strip() != final_compare["memory[70]_g"].astype(str).str.strip()
memory_70_Comp = memory_70_Comp.astype(int)
memory_71_Comp = final_compare["memory[71]"].astype(str).str.strip() != final_compare["memory[71]_g"].astype(str).str.strip()
memory_71_Comp = memory_71_Comp.astype(int)
memory_72_Comp = final_compare["memory[72]"].astype(str).str.strip() != final_compare["memory[72]_g"].astype(str).str.strip()
memory_72_Comp = memory_72_Comp.astype(int)
memory_73_Comp = final_compare["memory[73]"].astype(str).str.strip() != final_compare["memory[73]_g"].astype(str).str.strip()
memory_73_Comp = memory_73_Comp.astype(int)
memory_74_Comp = final_compare["memory[74]"].astype(str).str.strip() != final_compare["memory[74]_g"].astype(str).str.strip()
memory_74_Comp = memory_74_Comp.astype(int)
memory_75_Comp = final_compare["memory[75]"].astype(str).str.strip() != final_compare["memory[75]_g"].astype(str).str.strip()
memory_75_Comp = memory_75_Comp.astype(int)
memory_76_Comp = final_compare["memory[76]"].astype(str).str.strip() != final_compare["memory[76]_g"].astype(str).str.strip()
memory_76_Comp = memory_76_Comp.astype(int)
memory_77_Comp = final_compare["memory[77]"].astype(str).str.strip() != final_compare["memory[77]_g"].astype(str).str.strip()
memory_77_Comp = memory_77_Comp.astype(int)
memory_78_Comp = final_compare["memory[78]"].astype(str).str.strip() != final_compare["memory[78]_g"].astype(str).str.strip()
memory_78_Comp = memory_78_Comp.astype(int)
memory_79_Comp = final_compare["memory[79]"].astype(str).str.strip() != final_compare["memory[79]_g"].astype(str).str.strip()
memory_79_Comp = memory_79_Comp.astype(int)
memory_80_Comp = final_compare["memory[80]"].astype(str).str.strip() != final_compare["memory[80]_g"].astype(str).str.strip()
memory_80_Comp = memory_80_Comp.astype(int)
memory_90_Comp = final_compare["memory[90]"].astype(str).str.strip() != final_compare["memory[90]_g"].astype(str).str.strip()
memory_90_Comp = memory_90_Comp.astype(int)
memory_91_Comp = final_compare["memory[91]"].astype(str).str.strip() != final_compare["memory[91]_g"].astype(str).str.strip()
memory_91_Comp = memory_91_Comp.astype(int)

#-----------------------------------------

final_compare = final_compare.assign(memory_38_Comp = memory_38_Comp.values)
final_compare = final_compare.assign(memory_39_Comp = memory_39_Comp.values)
final_compare = final_compare.assign(memory_40_Comp = memory_40_Comp.values)
final_compare = final_compare.assign(memory_41_Comp = memory_41_Comp.values)
final_compare = final_compare.assign(memory_42_Comp = memory_42_Comp.values)
final_compare = final_compare.assign(memory_43_Comp = memory_43_Comp.values)
final_compare = final_compare.assign(memory_44_Comp = memory_44_Comp.values)
final_compare = final_compare.assign(memory_45_Comp = memory_45_Comp.values)
final_compare = final_compare.assign(memory_46_Comp = memory_46_Comp.values)
final_compare = final_compare.assign(memory_47_Comp = memory_47_Comp.values)
final_compare = final_compare.assign(memory_48_Comp = memory_48_Comp.values)
final_compare = final_compare.assign(memory_49_Comp = memory_49_Comp.values)
final_compare = final_compare.assign(memory_50_Comp = memory_50_Comp.values)
final_compare = final_compare.assign(memory_51_Comp = memory_51_Comp.values)
final_compare = final_compare.assign(memory_52_Comp = memory_52_Comp.values)
final_compare = final_compare.assign(memory_53_Comp = memory_53_Comp.values)
final_compare = final_compare.assign(memory_54_Comp = memory_54_Comp.values)
final_compare = final_compare.assign(memory_55_Comp = memory_55_Comp.values)
final_compare = final_compare.assign(memory_56_Comp = memory_56_Comp.values)
final_compare = final_compare.assign(memory_57_Comp = memory_57_Comp.values)
final_compare = final_compare.assign(memory_58_Comp = memory_58_Comp.values)
final_compare = final_compare.assign(memory_59_Comp = memory_59_Comp.values)
final_compare = final_compare.assign(memory_60_Comp = memory_60_Comp.values)
final_compare = final_compare.assign(memory_61_Comp = memory_61_Comp.values)
final_compare = final_compare.assign(memory_62_Comp = memory_62_Comp.values)
final_compare = final_compare.assign(memory_63_Comp = memory_63_Comp.values)
final_compare = final_compare.assign(memory_64_Comp = memory_64_Comp.values)
final_compare = final_compare.assign(memory_65_Comp = memory_65_Comp.values)
final_compare = final_compare.assign(memory_66_Comp = memory_66_Comp.values)
final_compare = final_compare.assign(memory_67_Comp = memory_67_Comp.values)
final_compare = final_compare.assign(memory_68_Comp = memory_68_Comp.values)
final_compare = final_compare.assign(memory_69_Comp = memory_69_Comp.values)
final_compare = final_compare.assign(memory_70_Comp = memory_70_Comp.values)
final_compare = final_compare.assign(memory_71_Comp = memory_71_Comp.values)
final_compare = final_compare.assign(memory_72_Comp = memory_72_Comp.values)
final_compare = final_compare.assign(memory_73_Comp = memory_73_Comp.values)
final_compare = final_compare.assign(memory_74_Comp = memory_74_Comp.values)
final_compare = final_compare.assign(memory_75_Comp = memory_75_Comp.values)
final_compare = final_compare.assign(memory_76_Comp = memory_76_Comp.values)
final_compare = final_compare.assign(memory_77_Comp = memory_77_Comp.values)
final_compare = final_compare.assign(memory_78_Comp = memory_78_Comp.values)
final_compare = final_compare.assign(memory_79_Comp = memory_79_Comp.values)
final_compare = final_compare.assign(memory_80_Comp = memory_80_Comp.values)

final_compare = final_compare.assign(memory_90_Comp = memory_90_Comp.values)
final_compare = final_compare.assign(memory_91_Comp = memory_91_Comp.values)

#final_compare["M/S"] = final_compare["memory_127_Comp"] + final_compare["memory_250_Comp"]
final_compare["M/S"] = final_compare["memory_38_Comp"]+final_compare["memory_39_Comp"]+final_compare["memory_40_Comp"] +final_compare["memory_41_Comp"]+final_compare["memory_42_Comp"]+final_compare["memory_43_Comp"]+final_compare["memory_44_Comp"] +final_compare["memory_45_Comp"]+final_compare["memory_46_Comp"]+final_compare["memory_47_Comp"]+final_compare["memory_48_Comp"] +final_compare["memory_49_Comp"]+final_compare["memory_50_Comp"]+final_compare["memory_51_Comp"]+final_compare["memory_52_Comp"] +final_compare["memory_53_Comp"]+final_compare["memory_54_Comp"]+final_compare["memory_55_Comp"]+final_compare["memory_56_Comp"] +final_compare["memory_57_Comp"]+final_compare["memory_58_Comp"]+final_compare["memory_59_Comp"]+final_compare["memory_60_Comp"] +final_compare["memory_61_Comp"]+final_compare["memory_62_Comp"]+final_compare["memory_63_Comp"]+final_compare["memory_64_Comp"] +final_compare["memory_65_Comp"]+final_compare["memory_66_Comp"]+final_compare["memory_67_Comp"]+final_compare["memory_68_Comp"] +final_compare["memory_69_Comp"]+final_compare["memory_70_Comp"]+final_compare["memory_71_Comp"]+final_compare["memory_72_Comp"]+final_compare["memory_73_Comp"]+final_compare["memory_74_Comp"]+final_compare["memory_75_Comp"] +final_compare["memory_76_Comp"]+final_compare["memory_77_Comp"]+final_compare["memory_78_Comp"]+final_compare["memory_79_Comp"] +final_compare["memory_80_Comp"]+final_compare["memory_90_Comp"]+final_compare["memory_91_Comp"] #+final_compare["memory_92_Comp"]+final_compare["memory_93_Comp"]+final_compare["memory_94_Comp"]+final_compare["memory_95_Comp"] +final_compare["memory_96_Comp"]+final_compare["memory_97_Comp"]+final_compare["memory_98_Comp"]+final_compare["memory_99_Comp"] +final_compare["memory_100_Comp"]+final_compare["memory_101_Comp"]+final_compare["memory_102_Comp"] +final_compare["memory_103_Comp"]+final_compare["memory_104_Comp"]+final_compare["memory_105_Comp"]+final_compare["memory_106_Comp"]+final_compare["memory_107_Comp"]+final_compare["memory_108_Comp"]+final_compare["memory_109_Comp"]+final_compare["memory_110_Comp"]+final_compare["memory_111_Comp"]+final_compare["memory_112_Comp"]+final_compare["memory_113_Comp"]+final_compare["memory_114_Comp"]+final_compare["memory_115_Comp"] +final_compare["memory_116_Comp"] +final_compare["memory_117_Comp"]+final_compare["memory_118_Comp"]+final_compare["memory_119_Comp"] +final_compare["memory_120_Comp"]+final_compare["memory_121_Comp"]+final_compare["memory_122_Comp"]+final_compare["memory_123_Comp"] +final_compare["memory_124_Comp"] +final_compare["memory_125_Comp"]+final_compare["memory_126_Comp"]+final_compare["memory_127_Comp"] +final_compare["memory_128_Comp"]+final_compare["memory_129_Comp"]+final_compare["memory_130_Comp"]+final_compare["memory_131_Comp"] +final_compare["memory_132_Comp"] +final_compare["memory_133_Comp"]+final_compare["memory_134_Comp"]+final_compare["memory_135_Comp"] +final_compare["memory_136_Comp"]+final_compare["memory_137_Comp"]+final_compare["memory_138_Comp"]+final_compare["memory_139_Comp"] +final_compare["memory_140_Comp"] +final_compare["memory_141_Comp"]+final_compare["memory_142_Comp"]+final_compare["memory_143_Comp"] +final_compare["memory_144_Comp"]+final_compare["memory_145_Comp"]+final_compare["memory_146_Comp"]+final_compare["memory_147_Comp"] +final_compare["memory_148_Comp"] +final_compare["memory_149_Comp"]+final_compare["memory_150_Comp"]+final_compare["memory_151_Comp"] +final_compare["memory_152_Comp"]+final_compare["memory_153_Comp"]+final_compare["memory_154_Comp"]+final_compare["memory_155_Comp"] +final_compare["memory_156_Comp"] +final_compare["memory_157_Comp"]+final_compare["memory_158_Comp"]+final_compare["memory_159_Comp"] +final_compare["memory_160_Comp"]+final_compare["memory_161_Comp"]+final_compare["memory_162_Comp"]+final_compare["memory_163_Comp"] +final_compare["memory_164_Comp"] +final_compare["memory_165_Comp"]+final_compare["memory_166_Comp"]+final_compare["memory_167_Comp"] +final_compare["memory_168_Comp"]+final_compare["memory_169_Comp"]+final_compare["memory_170_Comp"]+final_compare["memory_171_Comp"] +final_compare["memory_172_Comp"] +final_compare["memory_173_Comp"] +final_compare["memory_174_Comp"] +final_compare["memory_175_Comp"] +final_compare["memory_176_Comp"]+final_compare["memory_177_Comp"]+final_compare["memory_178_Comp"] +final_compare["memory_179_Comp"]+final_compare["memory_180_Comp"]+final_compare["memory_181_Comp"]+final_compare["memory_182_Comp"] +final_compare["memory_183_Comp"] +final_compare["memory_184_Comp"]+final_compare["memory_185_Comp"]+final_compare["memory_186_Comp"] +final_compare["memory_187_Comp"]+final_compare["memory_188_Comp"]+final_compare["memory_189_Comp"]+final_compare["memory_190_Comp"] +final_compare["memory_191_Comp"] +final_compare["memory_192_Comp"]+final_compare["memory_193_Comp"]+final_compare["memory_194_Comp"] +final_compare["memory_195_Comp"]+final_compare["memory_196_Comp"]+final_compare["memory_197_Comp"]+final_compare["memory_198_Comp"] +final_compare["memory_199_Comp"] +final_compare["memory_200_Comp"]+final_compare["memory_201_Comp"]+final_compare["memory_202_Comp"] +final_compare["memory_203_Comp"]+final_compare["memory_204_Comp"]+final_compare["memory_205_Comp"]+final_compare["memory_206_Comp"] +final_compare["memory_207_Comp"] +final_compare["memory_208_Comp"]+final_compare["memory_209_Comp"]+final_compare["memory_210_Comp"] +final_compare["memory_211_Comp"]+final_compare["memory_212_Comp"]+final_compare["memory_213_Comp"]+final_compare["memory_214_Comp"] +final_compare["memory_215_Comp"] +final_compare["memory_216_Comp"]+final_compare["memory_217_Comp"]+final_compare["memory_218_Comp"] +final_compare["memory_219_Comp"]+final_compare["memory_220_Comp"]+final_compare["memory_221_Comp"]+final_compare["memory_222_Comp"] +final_compare["memory_223_Comp"] +final_compare["memory_224_Comp"] +final_compare["memory_225_Comp"]+final_compare["memory_226_Comp"]+final_compare["memory_227_Comp"] +final_compare["memory_228_Comp"]+final_compare["memory_229_Comp"]+final_compare["memory_230_Comp"]+final_compare["memory_231_Comp"] +final_compare["memory_232_Comp"] +final_compare["memory_233_Comp"]+final_compare["memory_234_Comp"]+final_compare["memory_235_Comp"] +final_compare["memory_236_Comp"]+final_compare["memory_237_Comp"]+final_compare["memory_238_Comp"]+final_compare["memory_239_Comp"] +final_compare["memory_240_Comp"] +final_compare["memory_241_Comp"]+final_compare["memory_242_Comp"]+final_compare["memory_243_Comp"] +final_compare["memory_244_Comp"]+final_compare["memory_245_Comp"]+final_compare["memory_246_Comp"]+final_compare["memory_247_Comp"] +final_compare["memory_248_Comp"] +final_compare["memory_249_Comp"]+final_compare["memory_250_Comp"]+final_compare["memory_251_Comp"] +final_compare["memory_252_Comp"]+final_compare["memory_253_Comp"]+final_compare["memory_254_Comp"]+final_compare["memory_255_Comp"]
# final_compare.loc[final_compare['identifier'].duplicated(), 'identifier'] = ''
# print(final_compare)
# print(final_compare.head())
final_compare.to_csv("compare_with_regs_sim2.csv", index= False)
